package voxgig.bluefinshieldconexmgmtsdk.core

import java.util.{Map => JMap}

import voxgig.bluefinshieldconexmgmtsdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // A lazy val is initialised once, on first use, under a lock, so
  // concurrent first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private lazy val sharedConfigVal: JMap[String, Object] = makeConfig()

  def sharedConfig(): JMap[String, Object] = sharedConfigVal

  // The plugin definitions the model selected per feature, as List[Any] so a
  // feature consumes them without core naming a vendored type. Empty when no
  // active feature declares active plugin groups for this target.
  def featurePlugins(name: String): List[Any] = name match {
    case _ => Nil
  }

  def makeFeature(name: String): Feature = name match {
    case "audit" => new voxgig.bluefinshieldconexmgmtsdk.feature.AuditFeature()
    case "clienttrack" => new voxgig.bluefinshieldconexmgmtsdk.feature.ClienttrackFeature()
    case "idempotency" => new voxgig.bluefinshieldconexmgmtsdk.feature.IdempotencyFeature()
    case "log" => new voxgig.bluefinshieldconexmgmtsdk.feature.LogFeature()
    case "metrics" => new voxgig.bluefinshieldconexmgmtsdk.feature.MetricsFeature()
    case "paging" => new voxgig.bluefinshieldconexmgmtsdk.feature.PagingFeature()
    case "ratelimit" => new voxgig.bluefinshieldconexmgmtsdk.feature.RatelimitFeature()
    case "retry" => new voxgig.bluefinshieldconexmgmtsdk.feature.RetryFeature()
    case "telemetry" => new voxgig.bluefinshieldconexmgmtsdk.feature.TelemetryFeature()
    case "test" => new voxgig.bluefinshieldconexmgmtsdk.feature.TestFeature()
    case "timeout" => new voxgig.bluefinshieldconexmgmtsdk.feature.TimeoutFeature()
    case _ => new voxgig.bluefinshieldconexmgmtsdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinShieldconexMgmt\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"audit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"actor\": \"anonymous\",")
    b.append("    \"max\": 1000")
    b.append("   }")
    b.append("  },")
    b.append("  \"clienttrack\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"clientVersion\": \"0.0.1\"")
    b.append("   }")
    b.append("  },")
    b.append("  \"idempotency\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"header\": \"Idempotency-Key\",")
    b.append("    \"methods\": [")
    b.append("     \"POST\",")
    b.append("     \"PUT\",")
    b.append("     \"PATCH\",")
    b.append("     \"DELETE\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"create\",")
    b.append("     \"update\",")
    b.append("     \"remove\"")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"log\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": true")
    b.append("   }")
    b.append("  },")
    b.append("  \"metrics\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"paging\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"afterVar\": \"after\",")
    b.append("    \"cursorParam\": \"cursor\",")
    b.append("    \"firstVar\": \"first\",")
    b.append("    \"limitParam\": \"limit\",")
    b.append("    \"pageParam\": \"page\",")
    b.append("    \"startPage\": 1")
    b.append("   }")
    b.append("  },")
    b.append("  \"ratelimit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"burst\": 5,")
    b.append("    \"rate\": 5")
    b.append("   }")
    b.append("  },")
    b.append("  \"retry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"factor\": 2,")
    b.append("    \"maxDelay\": 2000,")
    b.append("    \"minDelay\": 50,")
    b.append("    \"retries\": 2,")
    b.append("    \"statuses\": [")
    b.append("     408,")
    b.append("     425,")
    b.append("     429,")
    b.append("     500,")
    b.append("     502,")
    b.append("     503,")
    b.append("     504")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"telemetry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"timeout\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"ms\": 30000")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://portal-cert.shieldconex.com:4010/api/v1\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Basic\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"client\": {},")
    b.append("   \"clone\": {},")
    b.append("   \"partner\": {},")
    b.append("   \"template\": {},")
    b.append("   \"transaction\": {},")
    b.append("   \"update_result\": {},")
    b.append("   \"user\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"client\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"billingId\",")
    b.append("     \"short\": \"Billing ID\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"contact\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      },")
    b.append("      \"list\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"created\",")
    b.append("     \"short\": \"Creation timestamp in ISO 8601 format.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"directPartner\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"This resource's unique identifier.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"isActive\",")
    b.append("     \"short\": \"This property indicates if the Client account is active or disabled.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mid\",")
    b.append("     \"short\": \"Some Partners will have an merchant ids on their own software offerings.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"modified\",")
    b.append("     \"short\": \"Last modified timestamp.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"The Client's name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"partner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"short\": \"The number of times that this resource has been updated.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"client\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"billing_id\",")
    b.append("          \"orig\": \"billing_id\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_email\",")
    b.append("          \"orig\": \"contact_email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_first_name\",")
    b.append("          \"orig\": \"contact_first_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_is_active\",")
    b.append("          \"orig\": \"contact_is_active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_last_name\",")
    b.append("          \"orig\": \"contact_last_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_phone\",")
    b.append("          \"orig\": \"contact_phone\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_send_welcome_email\",")
    b.append("          \"orig\": \"contact_send_welcome_email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_user_name\",")
    b.append("          \"orig\": \"contact_user_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_user_role\",")
    b.append("          \"orig\": \"contact_user_role\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"direct_partner_id\",")
    b.append("          \"orig\": \"direct_partner_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"direct_partner_name\",")
    b.append("          \"orig\": \"direct_partner_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"mid\",")
    b.append("          \"orig\": \"mid\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/clients\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"clients\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"billing_id\",")
    b.append("         \"contact_email\",")
    b.append("         \"contact_first_name\",")
    b.append("         \"contact_is_active\",")
    b.append("         \"contact_last_name\",")
    b.append("         \"contact_phone\",")
    b.append("         \"contact_send_welcome_email\",")
    b.append("         \"contact_user_name\",")
    b.append("         \"contact_user_role\",")
    b.append("         \"direct_partner_id\",")
    b.append("         \"direct_partner_name\",")
    b.append("         \"is_active\",")
    b.append("         \"mid\",")
    b.append("         \"name\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"clients\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 0,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"skip\",")
    b.append("          \"orig\": \"skip\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 10,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"take\",")
    b.append("          \"orig\": \"take\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/clients\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"clients\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"partner\",")
    b.append("         \"skip\",")
    b.append("         \"take\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"clients\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/clients/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"clients\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"clients\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/clients/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"clients\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"clients\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"clone\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"Unique identifier of newly added element.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"short\": \"Name of Template\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"clone\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"template_id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/templates/{id}/clone\",")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"id\": \"template_id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"template_id\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"clone\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"template_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\",")
    b.append("        \"{template_id}\",")
    b.append("        \"clone\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"template\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"partner\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"billingId\",")
    b.append("     \"short\": \"The Partner's billing identifier.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"contact\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      },")
    b.append("      \"list\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"created\",")
    b.append("     \"short\": \"Creation timestamp in ISO 8601 format.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"This resource's unique identifier.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"isActive\",")
    b.append("     \"short\": \"This property indicates if the Parter account is active or disabled.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"modified\",")
    b.append("     \"short\": \"Last modified timestamp.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"The Partner's name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"parent\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"The Partner's reference string.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"verificationPhrase\",")
    b.append("     \"short\": \"The verification phrase is a message that the Partner creates.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"short\": \"The number of times that this resource has been updated.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"partner\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"billing_id\",")
    b.append("          \"orig\": \"billing_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_email\",")
    b.append("          \"orig\": \"contact_email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_first_name\",")
    b.append("          \"orig\": \"contact_first_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_is_active\",")
    b.append("          \"orig\": \"contact_is_active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_last_name\",")
    b.append("          \"orig\": \"contact_last_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_phone\",")
    b.append("          \"orig\": \"contact_phone\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_send_welcome_email\",")
    b.append("          \"orig\": \"contact_send_welcome_email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_user_name\",")
    b.append("          \"orig\": \"contact_user_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_user_role\",")
    b.append("          \"orig\": \"contact_user_role\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"parent_id\",")
    b.append("          \"orig\": \"parent_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"parent_name\",")
    b.append("          \"orig\": \"parent_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"verification_phrase\",")
    b.append("          \"orig\": \"verification_phrase\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/partners\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"partners\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"billing_id\",")
    b.append("         \"contact_email\",")
    b.append("         \"contact_first_name\",")
    b.append("         \"contact_is_active\",")
    b.append("         \"contact_last_name\",")
    b.append("         \"contact_phone\",")
    b.append("         \"contact_send_welcome_email\",")
    b.append("         \"contact_user_name\",")
    b.append("         \"contact_user_role\",")
    b.append("         \"is_active\",")
    b.append("         \"name\",")
    b.append("         \"parent_id\",")
    b.append("         \"parent_name\",")
    b.append("         \"reference\",")
    b.append("         \"verification_phrase\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"partners\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 0,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"skip\",")
    b.append("          \"orig\": \"skip\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 10,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"take\",")
    b.append("          \"orig\": \"take\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/partners\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"partners\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"partner\",")
    b.append("         \"skip\",")
    b.append("         \"take\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"partners\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/partners/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"partners\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"partners\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"template\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"accessMode\",")
    b.append("     \"short\": \"The Template's access mode.\",")
    b.append("     \"type\": \"`$ANY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"active\",")
    b.append("     \"short\": \"This property indicates if the Template is active or inactive.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"client\",")
    b.append("     \"short\": \"Reference to the associated Client resource.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"fieldTemplates\",")
    b.append("     \"short\": \"Field Template list items\",")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"union\": {")
    b.append("      \"branches\": 9,")
    b.append("      \"count\": 1,")
    b.append("      \"depth\": 1")
    b.append("     }")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"Unique identifier of newly added element.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"short\": \"The Template's name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"options\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"partner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"The Template's unique reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"type\",")
    b.append("     \"short\": \"The Template's type.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"short\": \"The number of times that this resource has been updated.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"template\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"access_mode\",")
    b.append("          \"orig\": \"access_mode\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"active\",")
    b.append("          \"orig\": \"active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client_id\",")
    b.append("          \"orig\": \"client_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client_name\",")
    b.append("          \"orig\": \"client_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_template\",")
    b.append("          \"orig\": \"field_template\",")
    b.append("          \"type\": \"`$ARRAY`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_custom_style\",")
    b.append("          \"orig\": \"options_custom_style\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_custom_style_file\",")
    b.append("          \"orig\": \"options_custom_style_file\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_domain\",")
    b.append("          \"orig\": \"options_domain\",")
    b.append("          \"type\": \"`$ARRAY`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_active_from\",")
    b.append("          \"orig\": \"options_security_active_from\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_active_to\",")
    b.append("          \"orig\": \"options_security_active_to\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_irreversible\",")
    b.append("          \"orig\": \"options_security_irreversible\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_id\",")
    b.append("          \"orig\": \"partner_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_name\",")
    b.append("          \"orig\": \"partner_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"type\",")
    b.append("          \"orig\": \"type\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"version\",")
    b.append("          \"orig\": \"version\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/templates\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"access_mode\",")
    b.append("         \"active\",")
    b.append("         \"client_id\",")
    b.append("         \"client_name\",")
    b.append("         \"field_template\",")
    b.append("         \"name\",")
    b.append("         \"options_custom_style\",")
    b.append("         \"options_custom_style_file\",")
    b.append("         \"options_domain\",")
    b.append("         \"options_security_active_from\",")
    b.append("         \"options_security_active_to\",")
    b.append("         \"options_security_irreversible\",")
    b.append("         \"partner_id\",")
    b.append("         \"partner_name\",")
    b.append("         \"reference\",")
    b.append("         \"type\",")
    b.append("         \"version\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client\",")
    b.append("          \"orig\": \"client\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 0,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"skip\",")
    b.append("          \"orig\": \"skip\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 10,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"take\",")
    b.append("          \"orig\": \"take\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/templates\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client\",")
    b.append("         \"partner\",")
    b.append("         \"skip\",")
    b.append("         \"take\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/templates/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/templates/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"transaction\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"short\": \"BFID\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"client\",")
    b.append("     \"short\": \"Reference to the associated Client resource.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"completeDate\",")
    b.append("     \"short\": \"Timestamp from the beginning of the transaction.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"directPartner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"errCode\",")
    b.append("     \"short\": \"The error code that is sent in response to a failed decrypt API call.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"errMessage\",")
    b.append("     \"short\": \"The error messge that is sent in response to a failed decrypt API call.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"This resource's unique identifier.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ipAddress\",")
    b.append("     \"short\": \"The IP address of the http client that makes the decrypt API call.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message ID.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"partner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"The reference property that the Client includes in the decrypt API call.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"success\",")
    b.append("     \"short\": \"The success indicator.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int32\",")
    b.append("     \"name\": \"templateId\",")
    b.append("     \"short\": \"The Template's unique identifier.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"transaction\",")
    b.append("   \"op\": {")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client\",")
    b.append("          \"orig\": \"client\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"date_from\",")
    b.append("          \"orig\": \"date_from\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"date_to\",")
    b.append("          \"orig\": \"date_to\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"message_id\",")
    b.append("          \"orig\": \"message_id\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"paging_mode\",")
    b.append("          \"orig\": \"paging_mode\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 0,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"skip\",")
    b.append("          \"orig\": \"skip\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"success\",")
    b.append("          \"orig\": \"success\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 10,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"take\",")
    b.append("          \"orig\": \"take\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"transaction_type\",")
    b.append("          \"orig\": \"transaction_type\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/transactions\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"transactions\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client\",")
    b.append("         \"date_from\",")
    b.append("         \"date_to\",")
    b.append("         \"message_id\",")
    b.append("         \"paging_mode\",")
    b.append("         \"partner\",")
    b.append("         \"reference\",")
    b.append("         \"skip\",")
    b.append("         \"success\",")
    b.append("         \"take\",")
    b.append("         \"transaction_type\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"transactions\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"transaction_type\",")
    b.append("          \"orig\": \"transaction_type\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/transactions/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"transactions\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\",")
    b.append("         \"transaction_type\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"transactions\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"update_result\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"billingId\",")
    b.append("     \"short\": \"The Partner's billing identifier.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"client\",")
    b.append("     \"short\": \"Reference to the associated Client resource.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"contact\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"directPartner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The User's email address.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The User's name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"Unique identifier of newly added element.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"isActive\",")
    b.append("     \"short\": \"This property indicates if the User account is active or disabled.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The User's Surname.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mid\",")
    b.append("     \"short\": \"Some Partners will have an merchant ids on their own software offerings.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"short\": \"The Partner's name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"parent\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"partner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phone\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The User's phone number without dashes, spaces, or brackets (e.g.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"The Partner's reference string.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sendWelcomeEmail\",")
    b.append("     \"short\": \"If this property is set to 'true' the newly created user will be sent a welcome email.\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"userName\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The User's unique username.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"userRole\",")
    b.append("     \"op\": {")
    b.append("      \"list\": {")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      },")
    b.append("      \"update\": {")
    b.append("       \"type\": \"`$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Reference to the associated User Role.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"verificationPhrase\",")
    b.append("     \"short\": \"The verification phrase is a message that the Partner creates.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"short\": \"The number of times that this resource has been updated.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"update_result\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client\",")
    b.append("          \"orig\": \"client\",")
    b.append("          \"type\": \"`$OBJECT`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"email\",")
    b.append("          \"orig\": \"email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"first_name\",")
    b.append("          \"orig\": \"first_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"last_name\",")
    b.append("          \"orig\": \"last_name\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$OBJECT`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"phone\",")
    b.append("          \"orig\": \"phone\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"send_welcome_email\",")
    b.append("          \"orig\": \"send_welcome_email\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"user_role\",")
    b.append("          \"orig\": \"user_role\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$OBJECT`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"username\",")
    b.append("          \"orig\": \"username\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/users\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"users\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client\",")
    b.append("         \"email\",")
    b.append("         \"first_name\",")
    b.append("         \"is_active\",")
    b.append("         \"last_name\",")
    b.append("         \"partner\",")
    b.append("         \"phone\",")
    b.append("         \"send_welcome_email\",")
    b.append("         \"user_role\",")
    b.append("         \"username\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"users\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client\",")
    b.append("          \"orig\": \"client\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 0,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"skip\",")
    b.append("          \"orig\": \"skip\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"example\": 10,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"take\",")
    b.append("          \"orig\": \"take\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/users\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"users\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client\",")
    b.append("         \"partner\",")
    b.append("         \"skip\",")
    b.append("         \"take\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"users\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"update\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"update\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"access_mode\",")
    b.append("          \"orig\": \"access_mode\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"active\",")
    b.append("          \"orig\": \"active\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client_id\",")
    b.append("          \"orig\": \"client_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client_name\",")
    b.append("          \"orig\": \"client_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_template\",")
    b.append("          \"orig\": \"field_template\",")
    b.append("          \"type\": \"`$ARRAY`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_custom_style\",")
    b.append("          \"orig\": \"options_custom_style\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_custom_style_file\",")
    b.append("          \"orig\": \"options_custom_style_file\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_domain\",")
    b.append("          \"orig\": \"options_domain\",")
    b.append("          \"type\": \"`$ARRAY`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_active_from\",")
    b.append("          \"orig\": \"options_security_active_from\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_active_to\",")
    b.append("          \"orig\": \"options_security_active_to\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"options_security_irreversible\",")
    b.append("          \"orig\": \"options_security_irreversible\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_id\",")
    b.append("          \"orig\": \"partner_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_name\",")
    b.append("          \"orig\": \"partner_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"type\",")
    b.append("          \"orig\": \"type\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"version\",")
    b.append("          \"orig\": \"version\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PATCH\",")
    b.append("       \"orig\": \"/templates/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"templates\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"access_mode\",")
    b.append("         \"active\",")
    b.append("         \"client_id\",")
    b.append("         \"client_name\",")
    b.append("         \"field_template\",")
    b.append("         \"id\",")
    b.append("         \"name\",")
    b.append("         \"options_custom_style\",")
    b.append("         \"options_custom_style_file\",")
    b.append("         \"options_domain\",")
    b.append("         \"options_security_active_from\",")
    b.append("         \"options_security_active_to\",")
    b.append("         \"options_security_irreversible\",")
    b.append("         \"partner_id\",")
    b.append("         \"partner_name\",")
    b.append("         \"reference\",")
    b.append("         \"type\",")
    b.append("         \"version\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"templates\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"billing_id\",")
    b.append("          \"orig\": \"billing_id\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_id\",")
    b.append("          \"orig\": \"contact_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"parent_id\",")
    b.append("          \"orig\": \"parent_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"parent_name\",")
    b.append("          \"orig\": \"parent_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"verification_phrase\",")
    b.append("          \"orig\": \"verification_phrase\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"version\",")
    b.append("          \"orig\": \"version\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PATCH\",")
    b.append("       \"orig\": \"/partners/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"partners\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"billing_id\",")
    b.append("         \"contact_id\",")
    b.append("         \"id\",")
    b.append("         \"is_active\",")
    b.append("         \"name\",")
    b.append("         \"parent_id\",")
    b.append("         \"parent_name\",")
    b.append("         \"reference\",")
    b.append("         \"verification_phrase\",")
    b.append("         \"version\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"partners\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client\",")
    b.append("          \"orig\": \"client\",")
    b.append("          \"type\": \"`$OBJECT`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"email\",")
    b.append("          \"orig\": \"email\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"first_name\",")
    b.append("          \"orig\": \"first_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"last_name\",")
    b.append("          \"orig\": \"last_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner\",")
    b.append("          \"orig\": \"partner\",")
    b.append("          \"type\": \"`$OBJECT`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"phone\",")
    b.append("          \"orig\": \"phone\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"send_welcome_email\",")
    b.append("          \"orig\": \"send_welcome_email\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"username\",")
    b.append("          \"orig\": \"username\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PATCH\",")
    b.append("       \"orig\": \"/users/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"users\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client\",")
    b.append("         \"email\",")
    b.append("         \"first_name\",")
    b.append("         \"id\",")
    b.append("         \"is_active\",")
    b.append("         \"last_name\",")
    b.append("         \"partner\",")
    b.append("         \"phone\",")
    b.append("         \"send_welcome_email\",")
    b.append("         \"username\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"users\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"billing_id\",")
    b.append("          \"orig\": \"billing_id\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"contact_id\",")
    b.append("          \"orig\": \"contact_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"direct_partner_id\",")
    b.append("          \"orig\": \"direct_partner_id\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"direct_partner_name\",")
    b.append("          \"orig\": \"direct_partner_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"is_active\",")
    b.append("          \"orig\": \"is_active\",")
    b.append("          \"type\": \"`$BOOLEAN`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"mid\",")
    b.append("          \"orig\": \"mid\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"name\",")
    b.append("          \"orig\": \"name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"version\",")
    b.append("          \"orig\": \"version\",")
    b.append("          \"type\": \"`$INTEGER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PATCH\",")
    b.append("       \"orig\": \"/clients/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"clients\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"billing_id\",")
    b.append("         \"contact_id\",")
    b.append("         \"direct_partner_id\",")
    b.append("         \"direct_partner_name\",")
    b.append("         \"id\",")
    b.append("         \"is_active\",")
    b.append("         \"mid\",")
    b.append("         \"name\",")
    b.append("         \"version\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"clients\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"client\",")
    b.append("     \"short\": \"Reference to the associated Client resource.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"created\",")
    b.append("     \"short\": \"Creation timestamp in ISO 8601 format.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"int64\",")
    b.append("     \"name\": \"id\",")
    b.append("     \"short\": \"This resource's unique identifier.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"isActive\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"modified\",")
    b.append("     \"short\": \"Last modified timestamp.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"partner\",")
    b.append("     \"short\": \"Reference to the associated Partner.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phone\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"userName\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"userRole\",")
    b.append("     \"short\": \"Reference to the associated User Role.\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"short\": \"The number of times that this resource has been updated.\",")
    b.append("     \"type\": \"`$INTEGER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"id\": {")
    b.append("    \"field\": \"id\",")
    b.append("    \"name\": \"id\"")
    b.append("   },")
    b.append("   \"name\": \"user\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/users/{id}\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"users\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"var\": \"id\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"users\",")
    b.append("        \"{id}\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
