-- BluefinShieldconexMgmt SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Client
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "client" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "client" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "client" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "client" m co
end Client

namespace Clone
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "clone" d co
end Clone

namespace Partner
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "partner" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "partner" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "partner" m co
end Partner

namespace Template
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "template" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "template" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "template" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "template" m co
end Template

namespace Transaction
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "transaction" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "transaction" m co
end Transaction

namespace Update_result
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "update_result" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "update_result" m co
  def update (c m d co : Value) : SIO Value := SdkRuntime.opUpdate c "update_result" m d co
end Update_result

namespace User
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "user" m co
end User

