-- Typed models for the BluefinShieldconexMgmt SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Client
---@field billingId? string
---@field contact? table
---@field created? string
---@field directPartner? table
---@field id? number
---@field isActive? boolean
---@field mid? string
---@field modified? string
---@field name? string
---@field partner? table
---@field version? number

---@class ClientLoadMatch
---@field id string

---@class ClientListMatch
---@field billingId? string
---@field contact? table
---@field created? string
---@field directPartner? table
---@field id? number
---@field isActive? boolean
---@field mid? string
---@field modified? string
---@field name? string
---@field partner? table
---@field version? number

---@class ClientCreateData
---@field billingId? string
---@field contact? table
---@field created? string
---@field directPartner? table
---@field id? number
---@field isActive? boolean
---@field mid? string
---@field modified? string
---@field name? string
---@field partner? table
---@field version? number

---@class ClientRemoveMatch
---@field id string

---@class Clone
---@field id? number
---@field name? string

---@class CloneCreateData
---@field template_id string
---@field id? number
---@field name? string

---@class Partner
---@field billingId? string
---@field contact? table
---@field created? string
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field name? string
---@field parent? table
---@field reference? string
---@field verificationPhrase? string
---@field version? number

---@class PartnerLoadMatch
---@field id string

---@class PartnerListMatch
---@field billingId? string
---@field contact? table
---@field created? string
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field name? string
---@field parent? table
---@field reference? string
---@field verificationPhrase? string
---@field version? number

---@class PartnerCreateData
---@field billingId? string
---@field contact? table
---@field created? string
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field name? string
---@field parent? table
---@field reference? string
---@field verificationPhrase? string
---@field version? number

---@class Template
---@field accessMode? any
---@field active? boolean
---@field client? table
---@field fieldTemplates? table
---@field id? number
---@field name? string
---@field options? table
---@field partner? table
---@field reference? string
---@field type? string
---@field version? number

---@class TemplateLoadMatch
---@field id string

---@class TemplateListMatch
---@field accessMode? any
---@field active? boolean
---@field client? table
---@field fieldTemplates? table
---@field id? number
---@field name? string
---@field options? table
---@field partner? table
---@field reference? string
---@field type? string
---@field version? number

---@class TemplateCreateData
---@field accessMode? any
---@field active? boolean
---@field client? table
---@field fieldTemplates? table
---@field id? number
---@field name? string
---@field options? table
---@field partner? table
---@field reference? string
---@field type? string
---@field version? number

---@class TemplateRemoveMatch
---@field id string

---@class Transaction
---@field bfid? string
---@field client? table
---@field completeDate? string
---@field directPartner? table
---@field errCode? string
---@field errMessage? string
---@field id? number
---@field ipAddress? string
---@field messageId? string
---@field partner? table
---@field reference? string
---@field success? boolean
---@field templateId? string

---@class TransactionLoadMatch
---@field id string

---@class TransactionListMatch
---@field bfid? string
---@field client? table
---@field completeDate? string
---@field directPartner? table
---@field errCode? string
---@field errMessage? string
---@field id? number
---@field ipAddress? string
---@field messageId? string
---@field partner? table
---@field reference? string
---@field success? boolean
---@field templateId? string

---@class UpdateResult
---@field billingId? string
---@field client? table
---@field contact table
---@field directPartner? table
---@field email string
---@field firstName string
---@field id? number
---@field isActive? boolean
---@field lastName string
---@field mid? string
---@field name? string
---@field parent? table
---@field partner? table
---@field phone string
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName string
---@field userRole table
---@field verificationPhrase? string
---@field version? number

---@class UpdateResultListMatch
---@field billingId? string
---@field client? table
---@field contact? table
---@field directPartner? table
---@field email? string
---@field firstName? string
---@field id? number
---@field isActive? boolean
---@field lastName? string
---@field mid? string
---@field name? string
---@field parent? table
---@field partner? table
---@field phone? string
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName? string
---@field userRole? table
---@field verificationPhrase? string
---@field version? number

---@class UpdateResultCreateData
---@field billingId? string
---@field client? table
---@field contact table
---@field directPartner? table
---@field email string
---@field firstName string
---@field id? number
---@field isActive? boolean
---@field lastName string
---@field mid? string
---@field name? string
---@field parent? table
---@field partner? table
---@field phone string
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName string
---@field userRole table
---@field verificationPhrase? string
---@field version? number

---@class UpdateResultUpdateData
---@field id string
---@field billingId? string
---@field client? table
---@field contact? table
---@field directPartner? table
---@field email? string
---@field firstName? string
---@field isActive? boolean
---@field lastName? string
---@field mid? string
---@field name? string
---@field parent? table
---@field partner? table
---@field phone? string
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName? string
---@field userRole? table
---@field verificationPhrase? string
---@field version? number

---@class User
---@field client? table
---@field created? string
---@field email? string
---@field firstName? string
---@field id? number
---@field isActive? boolean
---@field lastName? string
---@field modified? string
---@field partner? table
---@field phone? string
---@field userName? string
---@field userRole? table
---@field version? number

---@class UserLoadMatch
---@field id string

local M = {}

return M
