-- Typed models for the BluefinShieldconexMgmt SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields{} and per-op
-- params (op.<name>.points[].g.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Client
---@field billingId? string
---@field contact? table
---@field created? string
---@field directPartner? table
---@field id? number
---@field isActive? boolean
---@field mid? string
---@field modified? string
---@field name? string
---@field partner? table
---@field version? number

---@class ClientLoadMatch
---@field id string

---@class ClientListMatch
---@field partner string
---@field skip? number
---@field take? number

---@class ClientCreateData
---@field billing_id? string
---@field contact_email string
---@field contact_first_name string
---@field contact_is_active boolean
---@field contact_last_name string
---@field contact_phone string
---@field contact_send_welcome_email boolean
---@field contact_user_name string
---@field contact_user_role string
---@field direct_partner_id number
---@field direct_partner_name string
---@field is_active boolean
---@field mid? string
---@field name string
---@field billingId? string
---@field contact? table
---@field created? string
---@field directPartner? table
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field partner? table
---@field version? number

---@class ClientRemoveMatch
---@field id string

---@class Clone
---@field id? number
---@field name? string

---@class CloneCreateData
---@field template_id string
---@field id? number
---@field name? string

---@class Partner
---@field billingId? string
---@field contact? table
---@field created? string
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field name? string
---@field parent? table
---@field reference? string
---@field verificationPhrase? string
---@field version? number

---@class PartnerLoadMatch
---@field id string

---@class PartnerListMatch
---@field partner? string
---@field skip? number
---@field take? number

---@class PartnerCreateData
---@field billing_id string
---@field contact_email string
---@field contact_first_name string
---@field contact_is_active boolean
---@field contact_last_name string
---@field contact_phone string
---@field contact_send_welcome_email boolean
---@field contact_user_name string
---@field contact_user_role string
---@field is_active boolean
---@field name string
---@field parent_id? number
---@field parent_name? string
---@field reference string
---@field verification_phrase? string
---@field billingId? string
---@field contact? table
---@field created? string
---@field id? number
---@field isActive? boolean
---@field modified? string
---@field parent? table
---@field verificationPhrase? string
---@field version? number

---@class Template
---@field accessMode? any
---@field active? boolean
---@field client? table
---@field fieldTemplates? table
---@field id? number
---@field name? string
---@field options? table
---@field partner? table
---@field reference? string
---@field type? string
---@field version? number

---@class TemplateLoadMatch
---@field id string

---@class TemplateListMatch
---@field client? string
---@field partner? string
---@field skip? number
---@field take? number

---@class TemplateCreateData
---@field access_mode? string
---@field active boolean
---@field client_id number
---@field client_name string
---@field field_template? table
---@field name string
---@field options_custom_style? string
---@field options_custom_style_file? string
---@field options_domain? table
---@field options_security_active_from? string
---@field options_security_active_to? string
---@field options_security_irreversible? boolean
---@field partner_id number
---@field partner_name string
---@field reference string
---@field type? string
---@field version? number
---@field accessMode? any
---@field client? table
---@field fieldTemplates? table
---@field id? number
---@field options? table
---@field partner? table

---@class TemplateRemoveMatch
---@field id string

---@class Transaction
---@field bfid? string
---@field client? table
---@field completeDate? string
---@field directPartner? table
---@field errCode? string
---@field errMessage? string
---@field id? number
---@field ipAddress? string
---@field messageId? string
---@field partner? table
---@field reference? string
---@field success? boolean
---@field templateId? string

---@class TransactionLoadMatch
---@field id string
---@field transaction_type? string

---@class TransactionListMatch
---@field client? string
---@field date_from? string
---@field date_to? string
---@field message_id? string
---@field paging_mode? string
---@field partner? string
---@field reference? string
---@field skip? number
---@field success? boolean
---@field take? number
---@field transaction_type? string

---@class UpdateResult
---@field billingId? string
---@field client? table
---@field contact table
---@field directPartner? table
---@field email string
---@field firstName string
---@field id? number
---@field isActive? boolean
---@field lastName string
---@field mid? string
---@field name? string
---@field parent? table
---@field partner? table
---@field phone string
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName string
---@field userRole table
---@field verificationPhrase? string
---@field version? number

---@class UpdateResultListMatch
---@field client? string
---@field partner? string
---@field skip? number
---@field take? number

---@class UpdateResultCreateData
---@field client? table
---@field email string
---@field first_name string
---@field is_active boolean
---@field last_name string
---@field partner? table
---@field phone number
---@field send_welcome_email boolean
---@field user_role table
---@field username string
---@field billingId? string
---@field contact table
---@field directPartner? table
---@field firstName string
---@field id? number
---@field isActive? boolean
---@field lastName string
---@field mid? string
---@field name? string
---@field parent? table
---@field reference? string
---@field sendWelcomeEmail? boolean
---@field userName string
---@field userRole table
---@field verificationPhrase? string
---@field version? number

---@class UpdateResultUpdateData
---@field id string
---@field access_mode? string
---@field active? boolean
---@field client_id? number
---@field client_name? string
---@field field_template? table
---@field name? string
---@field options_custom_style? string
---@field options_custom_style_file? string
---@field options_domain? table
---@field options_security_active_from? string
---@field options_security_active_to? string
---@field options_security_irreversible? boolean
---@field partner_id? number
---@field partner_name? string
---@field reference? string
---@field type? string
---@field version? number
---@field billing_id? string
---@field contact_id? number
---@field is_active? boolean
---@field parent_id? number
---@field parent_name? string
---@field verification_phrase? string
---@field client? table
---@field email? string
---@field first_name? string
---@field last_name? string
---@field partner? table
---@field phone? number
---@field send_welcome_email? boolean
---@field username? string
---@field direct_partner_id? number
---@field direct_partner_name? string
---@field mid? string
---@field billingId? string
---@field contact? table
---@field directPartner? table
---@field firstName? string
---@field isActive? boolean
---@field lastName? string
---@field parent? table
---@field sendWelcomeEmail? boolean
---@field userName? string
---@field userRole? table
---@field verificationPhrase? string

---@class User
---@field client? table
---@field created? string
---@field email? string
---@field firstName? string
---@field id? number
---@field isActive? boolean
---@field lastName? string
---@field modified? string
---@field partner? table
---@field phone? string
---@field userName? string
---@field userRole? table
---@field version? number

---@class UserLoadMatch
---@field id string

local M = {}

return M
