// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinShieldconexMgmt")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://portal-cert.shieldconex.com:4010/api/v1"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(7,
        "client", v_map(),
        "clone", v_map(),
        "partner", v_map(),
        "template", v_map(),
        "transaction", v_map(),
        "update_result", v_map(),
        "user", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(7,
      "client", cmap(4,
        "fields", clist(11,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("billing_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("contact"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("created"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("direct_partner"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("is_active"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("modified"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("name"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(10))),
        "name", v_str("client"),
        "op", cmap(4,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(14,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", cmap(1,
                  "exist", clist(14,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create")),
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(3,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("GET"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list")),
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(7,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"),
                      "index$", v_num(0)))),
                "method", v_str("GET"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load")),
          "remove", cmap(4,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("DELETE"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("remove"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "clone", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("clone"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("template_id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/templates/{id}/clone"),
                "parts", clist(3,
                  v_str("templates"),
                  v_str("{template_id}"),
                  v_str("clone")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "id", v_str("template_id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("template_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("template"))))),
      "partner", cmap(4,
        "fields", clist(11,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("billing_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("contact"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("created"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("is_active"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("modified"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("name"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("parent"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("verification_phrase"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(10))),
        "name", v_str("partner"),
        "op", cmap(3,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(15,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", cmap(1,
                  "exist", clist(15,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create")),
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(3,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("GET"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list")),
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(7,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"),
                      "index$", v_num(0)))),
                "method", v_str("GET"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "template", cmap(4,
        "fields", clist(11,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("access_mode"),
            "req", v_bool(false),
            "type", v_str("`$ANY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("active"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("field_template"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("option"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("type"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(10))),
        "name", v_str("template"),
        "op", cmap(4,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(17,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "reqd", v_bool(false),
                      "type", v_str("`$ARRAY`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "reqd", v_bool(false),
                      "type", v_str("`$ARRAY`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("POST"),
                "orig", v_str("/templates"),
                "parts", clist(1,
                  v_str("templates")),
                "select", cmap(1,
                  "exist", clist(17,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create")),
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("GET"),
                "orig", v_str("/templates"),
                "parts", clist(1,
                  v_str("templates")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list")),
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load")),
          "remove", cmap(4,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("DELETE"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("remove"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transaction", cmap(4,
        "fields", clist(13,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("bfid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("complete_date"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("direct_partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("err_code"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("err_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("ip_address"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("success"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("template_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12))),
        "name", v_str("transaction"),
        "op", cmap(2,
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(11,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("date_from"),
                      "orig", v_str("date_from"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("date_to"),
                      "orig", v_str("date_to"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("message_id"),
                      "orig", v_str("message_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("paging_mode"),
                      "orig", v_str("paging_mode"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("success"),
                      "orig", v_str("success"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/transactions"),
                "parts", clist(1,
                  v_str("transactions")),
                "select", cmap(1,
                  "exist", clist(11,
                    v_str("client"),
                    v_str("date_from"),
                    v_str("date_to"),
                    v_str("message_id"),
                    v_str("paging_mode"),
                    v_str("partner"),
                    v_str("reference"),
                    v_str("skip"),
                    v_str("success"),
                    v_str("take"),
                    v_str("transaction_type"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list")),
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/transactions/{id}"),
                "parts", clist(2,
                  v_str("transactions"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("transaction_type"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_result", cmap(4,
        "fields", clist(20,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("billing_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("contact"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("direct_partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("email"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("is_active"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(7)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("parent"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(12)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("phone"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("send_welcome_email"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(15)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("user_name"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("user_role"),
            "op", cmap(2,
              "list", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$OBJECT`")),
              "update", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("verification_phrase"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(19))),
        "name", v_str("update_result"),
        "op", cmap(3,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(10,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(false),
                      "type", v_str("`$OBJECT`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$OBJECT`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("user_role"),
                      "orig", v_str("user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$OBJECT`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("user_role"),
                    v_str("username"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create")),
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("GET"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list")),
          "update", cmap(4,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(4,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(17,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "reqd", v_bool(false),
                      "type", v_str("`$ARRAY`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "reqd", v_bool(false),
                      "type", v_str("`$ARRAY`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("PATCH"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(18,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("id"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(9,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("PATCH"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(9,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(false),
                      "type", v_str("`$OBJECT`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(false),
                      "type", v_str("`$OBJECT`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("PATCH"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("username"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(8,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(false),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "reqd", v_bool(false),
                      "type", v_str("`$INTEGER`")))),
                "method", v_str("PATCH"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(9,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3))),
            "key$", v_str("update"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "user", cmap(4,
        "fields", clist(13,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("created"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("is_active"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("modified"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("user_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("user_role"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(12))),
        "name", v_str("user"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "cache") == 0) return feature_cache_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "netsim") == 0) return feature_netsim_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "proxy") == 0) return feature_proxy_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "rbac") == 0) return feature_rbac_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "streaming") == 0) return feature_streaming_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}
