// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinShieldconexMgmt"),
      "slug", v_str("bluefin-shieldconex-mgmt"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base"))),
    "options", cmap(4,
      "base", v_str("https://portal-cert.shieldconex.com:4010/api/v1"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(7,
        "client", v_map(),
        "clone", v_map(),
        "partner", v_map(),
        "template", v_map(),
        "transaction", v_map(),
        "update_result", v_map(),
        "user", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(7,
      "client", cmap(4,
        "fields", clist(11,
          cmap(3,
            "name", v_str("billingId"),
            "short", v_str("Billing ID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("contact"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("created"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("directPartner"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("This resource's unique identifier."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("isActive"),
            "short", v_str("This property indicates if the Client account is active or disabled."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("mid"),
            "short", v_str("Some Partners will have an merchant ids on their own software offerings."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modified"),
            "short", v_str("Last modified timestamp."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("name"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The Client's name."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("partner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("version"),
            "short", v_str("The number of times that this resource has been updated."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("client"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(14,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", cmap(1,
                  "exist", clist(14,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "clone", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("id"),
            "short", v_str("Unique identifier of newly added element."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("Name of Template"),
            "type", v_str("`$STRING`"))),
        "name", v_str("clone"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("template_id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/templates/{id}/clone"),
                "parts", clist(3,
                  v_str("templates"),
                  v_str("{template_id}"),
                  v_str("clone")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "id", v_str("template_id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("template_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("template"))))),
      "partner", cmap(4,
        "fields", clist(11,
          cmap(3,
            "name", v_str("billingId"),
            "short", v_str("The Partner's billing identifier."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("contact"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("created"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("This resource's unique identifier."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("isActive"),
            "short", v_str("This property indicates if the Parter account is active or disabled."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("modified"),
            "short", v_str("Last modified timestamp."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("name"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The Partner's name."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("parent"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("The Partner's reference string."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("verificationPhrase"),
            "short", v_str("The verification phrase is a message that the Partner creates."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("version"),
            "short", v_str("The number of times that this resource has been updated."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("partner"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(15,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", cmap(1,
                  "exist", clist(15,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "template", cmap(4,
        "fields", clist(11,
          cmap(3,
            "name", v_str("accessMode"),
            "short", v_str("The Template's access mode."),
            "type", v_str("`$ANY`")),
          cmap(3,
            "name", v_str("active"),
            "short", v_str("This property indicates if the Template is active or inactive."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("client"),
            "short", v_str("Reference to the associated Client resource."),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("fieldTemplates"),
            "short", v_str("Field Template list items"),
            "type", v_str("`$ARRAY`"),
            "union", cmap(3,
              "branches", v_num(9),
              "count", v_num(1),
              "depth", v_num(1))),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("Unique identifier of newly added element."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("The Template's name."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("options"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("partner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("The Template's unique reference."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("type"),
            "short", v_str("The Template's type."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("version"),
            "short", v_str("The number of times that this resource has been updated."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("template"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(17,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "type", v_str("`$ARRAY`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "type", v_str("`$ARRAY`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/templates"),
                "parts", clist(1,
                  v_str("templates")),
                "select", cmap(1,
                  "exist", clist(17,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/templates"),
                "parts", clist(1,
                  v_str("templates")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transaction", cmap(4,
        "fields", clist(13,
          cmap(3,
            "name", v_str("bfid"),
            "short", v_str("BFID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("client"),
            "short", v_str("Reference to the associated Client resource."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("completeDate"),
            "short", v_str("Timestamp from the beginning of the transaction."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("directPartner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("errCode"),
            "short", v_str("The error code that is sent in response to a failed decrypt API call."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("errMessage"),
            "short", v_str("The error messge that is sent in response to a failed decrypt API call."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("This resource's unique identifier."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("ipAddress"),
            "short", v_str("The IP address of the http client that makes the decrypt API call."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message ID."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("partner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("The reference property that the Client includes in the decrypt API call."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("success"),
            "short", v_str("The success indicator."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("templateId"),
            "short", v_str("The Template's unique identifier."),
            "type", v_str("`$STRING`"))),
        "name", v_str("transaction"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(11,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("date_from"),
                      "orig", v_str("date_from"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("date_to"),
                      "orig", v_str("date_to"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("message_id"),
                      "orig", v_str("message_id"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("paging_mode"),
                      "orig", v_str("paging_mode"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("success"),
                      "orig", v_str("success"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions"),
                "parts", clist(1,
                  v_str("transactions")),
                "select", cmap(1,
                  "exist", clist(11,
                    v_str("client"),
                    v_str("date_from"),
                    v_str("date_to"),
                    v_str("message_id"),
                    v_str("paging_mode"),
                    v_str("partner"),
                    v_str("reference"),
                    v_str("skip"),
                    v_str("success"),
                    v_str("take"),
                    v_str("transaction_type"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(1,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions/{id}"),
                "parts", clist(2,
                  v_str("transactions"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("transaction_type"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_result", cmap(4,
        "fields", clist(20,
          cmap(3,
            "name", v_str("billingId"),
            "short", v_str("The Partner's billing identifier."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("client"),
            "short", v_str("Reference to the associated Client resource."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("contact"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("directPartner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(5,
            "name", v_str("email"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("The User's email address."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("firstName"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("The User's name."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("Unique identifier of newly added element."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("isActive"),
            "short", v_str("This property indicates if the User account is active or disabled."),
            "type", v_str("`$BOOLEAN`")),
          cmap(5,
            "name", v_str("lastName"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("The User's Surname."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("mid"),
            "short", v_str("Some Partners will have an merchant ids on their own software offerings."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("The Partner's name."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("parent"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("partner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(5,
            "name", v_str("phone"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("The User's phone number without dashes, spaces, or brackets (e.g."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("The Partner's reference string."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sendWelcomeEmail"),
            "short", v_str("If this property is set to 'true' the newly created user will be sent a welcome email."),
            "type", v_str("`$BOOLEAN`")),
          cmap(5,
            "name", v_str("userName"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("The User's unique username."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("userRole"),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$OBJECT`")),
              "update", cmap(1,
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(true),
            "short", v_str("Reference to the associated User Role."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("verificationPhrase"),
            "short", v_str("The verification phrase is a message that the Partner creates."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("version"),
            "short", v_str("The number of times that this resource has been updated."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("update_result"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(10,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$OBJECT`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$OBJECT`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "reqd", v_bool(true),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "reqd", v_bool(true),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("user_role"),
                      "orig", v_str("user_role"),
                      "reqd", v_bool(true),
                      "type", v_str("`$OBJECT`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("user_role"),
                    v_str("username"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(4,
              cmap(7,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(17,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "type", v_str("`$ARRAY`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "type", v_str("`$ARRAY`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/templates/{id}"),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(18,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("id"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(9,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(9,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$OBJECT`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$OBJECT`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("username"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(8,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(9,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name"),
                    v_str("version"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "user", cmap(4,
        "fields", clist(13,
          cmap(3,
            "name", v_str("client"),
            "short", v_str("Reference to the associated Client resource."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("created"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("email"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("firstName"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "short", v_str("This resource's unique identifier."),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("lastName"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modified"),
            "short", v_str("Last modified timestamp."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("partner"),
            "short", v_str("Reference to the associated Partner."),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("phone"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userName"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("userRole"),
            "short", v_str("Reference to the associated User Role."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("version"),
            "short", v_str("The number of times that this resource has been updated."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("user"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
