// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinShieldconexMgmt"),
      "slug", v_str("bluefin-shieldconex-mgmt"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(12,
      "audit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "actor", v_str("anonymous"),
          "max", v_num(1000)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sink", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "clienttrack", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "clientVersion", v_str("0.0.1")),
        "optspec", cmap(5,
          "clientName", v_str("`$STRING`"),
          "clientVersion", v_str("`$STRING`"),
          "headers", v_str("`$MAP`"),
          "idgen", v_str("`$FUNCTION`"),
          "sessionId", v_str("`$STRING`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "log", cmap(4,
        "options", cmap(1,
          "active", v_bool(true)),
        "optspec", cmap(2,
          "level", v_str("`$STRING`"),
          "logger", v_str("`$ANY`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "telemetry", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(4,
          "exporter", v_str("`$FUNCTION`"),
          "headers", v_str("`$MAP`"),
          "idgen", v_str("`$FUNCTION`"),
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://portal-cert.shieldconex.com:4010/api/v1"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(7,
        "client", v_map(),
        "clone", v_map(),
        "partner", v_map(),
        "template", v_map(),
        "transaction", v_map(),
        "update_result", v_map(),
        "user", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(7,
      "client", cmap(5,
        "fields", clist(11,
          cmap(4,
            "name", v_str("billingId"),
            "title", v_str("Billing Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("Billing ID")),
          cmap(4,
            "name", v_str("contact"),
            "title", v_str("Contact"),
            "type", v_str("`$OBJECT`"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")))),
          cmap(5,
            "name", v_str("created"),
            "title", v_str("Created"),
            "type", v_str("`$STRING`"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "format", v_str("date-time")),
          cmap(5,
            "name", v_str("directPartner"),
            "title", v_str("Direct Partner"),
            "type", v_str("`$OBJECT`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "short", v_str("Reference to the associated Partner.")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("This resource's unique identifier."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("isActive"),
            "title", v_str("Is Active"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("This property indicates if the Client account is active or disabled.")),
          cmap(4,
            "name", v_str("mid"),
            "title", v_str("Mid"),
            "type", v_str("`$STRING`"),
            "short", v_str("Some Partners will have an merchant ids on their own software offerings.")),
          cmap(5,
            "name", v_str("modified"),
            "title", v_str("Modified"),
            "type", v_str("`$STRING`"),
            "short", v_str("Last modified timestamp."),
            "format", v_str("date-time")),
          cmap(5,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The Client's name.")),
          cmap(4,
            "name", v_str("partner"),
            "title", v_str("Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("The number of times that this resource has been updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("client"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/clients"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("clients"))),
                "parts", clist(1,
                  v_str("clients")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "query", clist(14,
                    cmap(4,
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(14,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name")))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("clients"))),
                "parts", clist(1,
                  v_str("clients")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "args", cmap(1,
                  "query", clist(3,
                    cmap(5,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(0)),
                    cmap(5,
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(10)))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("clients")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/clients/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("clients")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "clone", cmap(5,
        "fields", clist(2,
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Unique identifier of newly added element."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "short", v_str("Name of Template"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("clone"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/templates/{id}/clone"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("templates")),
                  cmap(1,
                    "var", v_str("template_id")),
                  cmap(1,
                    "lit", v_str("clone"))),
                "parts", clist(3,
                  v_str("templates"),
                  v_str("{template_id}"),
                  v_str("clone")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "id", v_str("template_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("template_id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("template_id"))))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("$.main.kit.entity.template"))))),
      "partner", cmap(5,
        "fields", clist(11,
          cmap(4,
            "name", v_str("billingId"),
            "title", v_str("Billing Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Partner's billing identifier.")),
          cmap(4,
            "name", v_str("contact"),
            "title", v_str("Contact"),
            "type", v_str("`$OBJECT`"),
            "op", cmap(2,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")),
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`")))),
          cmap(5,
            "name", v_str("created"),
            "title", v_str("Created"),
            "type", v_str("`$STRING`"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "format", v_str("date-time")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("This resource's unique identifier."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("isActive"),
            "title", v_str("Is Active"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("This property indicates if the Parter account is active or disabled.")),
          cmap(5,
            "name", v_str("modified"),
            "title", v_str("Modified"),
            "type", v_str("`$STRING`"),
            "short", v_str("Last modified timestamp."),
            "format", v_str("date-time")),
          cmap(5,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The Partner's name.")),
          cmap(5,
            "name", v_str("parent"),
            "title", v_str("Parent"),
            "type", v_str("`$OBJECT`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("reference"),
            "title", v_str("Reference"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Partner's reference string.")),
          cmap(4,
            "name", v_str("verificationPhrase"),
            "title", v_str("Verification Phrase"),
            "type", v_str("`$STRING`"),
            "short", v_str("The verification phrase is a message that the Partner creates.")),
          cmap(4,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("The number of times that this resource has been updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("partner"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/partners"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("partners"))),
                "parts", clist(1,
                  v_str("partners")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "query", clist(15,
                    cmap(5,
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_email"),
                      "orig", v_str("contact_email"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_first_name"),
                      "orig", v_str("contact_first_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_is_active"),
                      "orig", v_str("contact_is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_last_name"),
                      "orig", v_str("contact_last_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_phone"),
                      "orig", v_str("contact_phone"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_send_welcome_email"),
                      "orig", v_str("contact_send_welcome_email"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_user_name"),
                      "orig", v_str("contact_user_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("contact_user_role"),
                      "orig", v_str("contact_user_role"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(15,
                    v_str("billing_id"),
                    v_str("contact_email"),
                    v_str("contact_first_name"),
                    v_str("contact_is_active"),
                    v_str("contact_last_name"),
                    v_str("contact_phone"),
                    v_str("contact_send_welcome_email"),
                    v_str("contact_user_name"),
                    v_str("contact_user_role"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase")))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("partners"))),
                "parts", clist(1,
                  v_str("partners")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "args", cmap(1,
                  "query", clist(3,
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(0)),
                    cmap(5,
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(10)))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("partners")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "template", cmap(5,
        "fields", clist(11,
          cmap(4,
            "name", v_str("accessMode"),
            "title", v_str("Access Mode"),
            "type", v_str("`$ANY`"),
            "short", v_str("The Template's access mode.")),
          cmap(4,
            "name", v_str("active"),
            "title", v_str("Active"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("This property indicates if the Template is active or inactive.")),
          cmap(4,
            "name", v_str("client"),
            "title", v_str("Client"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Client resource.")),
          cmap(4,
            "name", v_str("fieldTemplates"),
            "title", v_str("Field Templates"),
            "type", v_str("`$ARRAY`"),
            "short", v_str("Field Template list items")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Unique identifier of newly added element."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Template's name.")),
          cmap(3,
            "name", v_str("options"),
            "title", v_str("Options"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("partner"),
            "title", v_str("Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("reference"),
            "title", v_str("Reference"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Template's unique reference.")),
          cmap(4,
            "name", v_str("type"),
            "title", v_str("Type"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Template's type.")),
          cmap(4,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("The number of times that this resource has been updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("template"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/templates"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("templates"))),
                "parts", clist(1,
                  v_str("templates")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "query", clist(17,
                    cmap(4,
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "type", v_str("`$ARRAY`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "type", v_str("`$ARRAY`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(17,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version")))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/templates"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("templates"))),
                "parts", clist(1,
                  v_str("templates")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(0)),
                    cmap(5,
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(10)))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/templates/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("templates")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/templates/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("templates")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transaction", cmap(5,
        "fields", clist(13,
          cmap(4,
            "name", v_str("bfid"),
            "title", v_str("Bfid"),
            "type", v_str("`$STRING`"),
            "short", v_str("BFID")),
          cmap(4,
            "name", v_str("client"),
            "title", v_str("Client"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Client resource.")),
          cmap(5,
            "name", v_str("completeDate"),
            "title", v_str("Complete Date"),
            "type", v_str("`$STRING`"),
            "short", v_str("Timestamp from the beginning of the transaction."),
            "format", v_str("date-time")),
          cmap(4,
            "name", v_str("directPartner"),
            "title", v_str("Direct Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("errCode"),
            "title", v_str("Err Code"),
            "type", v_str("`$STRING`"),
            "short", v_str("The error code that is sent in response to a failed decrypt API call.")),
          cmap(4,
            "name", v_str("errMessage"),
            "title", v_str("Err Message"),
            "type", v_str("`$STRING`"),
            "short", v_str("The error messge that is sent in response to a failed decrypt API call.")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("This resource's unique identifier."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("ipAddress"),
            "title", v_str("Ip Address"),
            "type", v_str("`$STRING`"),
            "short", v_str("The IP address of the http client that makes the decrypt API call.")),
          cmap(4,
            "name", v_str("messageId"),
            "title", v_str("Message Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("Message ID.")),
          cmap(4,
            "name", v_str("partner"),
            "title", v_str("Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("reference"),
            "title", v_str("Reference"),
            "type", v_str("`$STRING`"),
            "short", v_str("The reference property that the Client includes in the decrypt API call.")),
          cmap(4,
            "name", v_str("success"),
            "title", v_str("Success"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("The success indicator.")),
          cmap(5,
            "name", v_str("templateId"),
            "title", v_str("Template Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Template's unique identifier."),
            "format", v_str("int32"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("transaction"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("transactions"))),
                "parts", clist(1,
                  v_str("transactions")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "args", cmap(1,
                  "query", clist(11,
                    cmap(4,
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("date_from"),
                      "orig", v_str("date_from"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("date_to"),
                      "orig", v_str("date_to"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("message_id"),
                      "orig", v_str("message_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("paging_mode"),
                      "orig", v_str("paging_mode"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(0)),
                    cmap(4,
                      "name", v_str("success"),
                      "orig", v_str("success"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(10)),
                    cmap(4,
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(11,
                    v_str("client"),
                    v_str("date_from"),
                    v_str("date_to"),
                    v_str("message_id"),
                    v_str("paging_mode"),
                    v_str("partner"),
                    v_str("reference"),
                    v_str("skip"),
                    v_str("success"),
                    v_str("take"),
                    v_str("transaction_type")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("transactions")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("transactions"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("transaction_type"),
                      "orig", v_str("transaction_type"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("transaction_type"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_result", cmap(5,
        "fields", clist(20,
          cmap(4,
            "name", v_str("billingId"),
            "title", v_str("Billing Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Partner's billing identifier.")),
          cmap(4,
            "name", v_str("client"),
            "title", v_str("Client"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Client resource.")),
          cmap(4,
            "name", v_str("contact"),
            "title", v_str("Contact"),
            "type", v_str("`$OBJECT`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("directPartner"),
            "title", v_str("Direct Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(6,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "short", v_str("The User's email address.")),
          cmap(6,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "short", v_str("The User's name.")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Unique identifier of newly added element."),
            "format", v_str("int64")),
          cmap(4,
            "name", v_str("isActive"),
            "title", v_str("Is Active"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("This property indicates if the User account is active or disabled.")),
          cmap(6,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "short", v_str("The User's Surname.")),
          cmap(4,
            "name", v_str("mid"),
            "title", v_str("Mid"),
            "type", v_str("`$STRING`"),
            "short", v_str("Some Partners will have an merchant ids on their own software offerings.")),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Partner's name.")),
          cmap(4,
            "name", v_str("parent"),
            "title", v_str("Parent"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(4,
            "name", v_str("partner"),
            "title", v_str("Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(6,
            "name", v_str("phone"),
            "title", v_str("Phone"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "short", v_str("The User's phone number without dashes, spaces, or brackets (e.g.")),
          cmap(4,
            "name", v_str("reference"),
            "title", v_str("Reference"),
            "type", v_str("`$STRING`"),
            "short", v_str("The Partner's reference string.")),
          cmap(4,
            "name", v_str("sendWelcomeEmail"),
            "title", v_str("Send Welcome Email"),
            "type", v_str("`$BOOLEAN`"),
            "short", v_str("If this property is set to 'true' the newly created user will be sent a welcome email.")),
          cmap(6,
            "name", v_str("userName"),
            "title", v_str("User Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$STRING`")),
              "update", cmap(1,
                "type", v_str("`$STRING`"))),
            "short", v_str("The User's unique username.")),
          cmap(6,
            "name", v_str("userRole"),
            "title", v_str("User Role"),
            "type", v_str("`$OBJECT`"),
            "req", v_bool(true),
            "op", cmap(2,
              "list", cmap(1,
                "type", v_str("`$OBJECT`")),
              "update", cmap(1,
                "type", v_str("`$OBJECT`"))),
            "short", v_str("Reference to the associated User Role.")),
          cmap(4,
            "name", v_str("verificationPhrase"),
            "title", v_str("Verification Phrase"),
            "type", v_str("`$STRING`"),
            "short", v_str("The verification phrase is a message that the Partner creates.")),
          cmap(4,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("The number of times that this resource has been updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("update_result"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/users"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("users"))),
                "parts", clist(1,
                  v_str("users")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "query", clist(10,
                    cmap(4,
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$OBJECT`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$OBJECT`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("user_role"),
                      "orig", v_str("user_role"),
                      "type", v_str("`$OBJECT`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("user_role"),
                    v_str("username")))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("users"))),
                "parts", clist(1,
                  v_str("users")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(0)),
                    cmap(5,
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(10)))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("client"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(4,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/templates/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("templates")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("templates"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(17,
                    cmap(4,
                      "name", v_str("access_mode"),
                      "orig", v_str("access_mode"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("active"),
                      "orig", v_str("active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("client_name"),
                      "orig", v_str("client_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("field_template"),
                      "orig", v_str("field_template"),
                      "type", v_str("`$ARRAY`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_custom_style"),
                      "orig", v_str("options_custom_style"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_custom_style_file"),
                      "orig", v_str("options_custom_style_file"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_domain"),
                      "orig", v_str("options_domain"),
                      "type", v_str("`$ARRAY`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_active_from"),
                      "orig", v_str("options_security_active_from"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_active_to"),
                      "orig", v_str("options_security_active_to"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("options_security_irreversible"),
                      "orig", v_str("options_security_irreversible"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner_name"),
                      "orig", v_str("partner_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("type"),
                      "orig", v_str("type"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(18,
                    v_str("access_mode"),
                    v_str("active"),
                    v_str("client_id"),
                    v_str("client_name"),
                    v_str("field_template"),
                    v_str("id"),
                    v_str("name"),
                    v_str("options_custom_style"),
                    v_str("options_custom_style_file"),
                    v_str("options_domain"),
                    v_str("options_security_active_from"),
                    v_str("options_security_active_to"),
                    v_str("options_security_irreversible"),
                    v_str("partner_id"),
                    v_str("partner_name"),
                    v_str("reference"),
                    v_str("type"),
                    v_str("version")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/partners/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("partners")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(9,
                    cmap(4,
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("parent_id"),
                      "orig", v_str("parent_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("parent_name"),
                      "orig", v_str("parent_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("verification_phrase"),
                      "orig", v_str("verification_phrase"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("name"),
                    v_str("parent_id"),
                    v_str("parent_name"),
                    v_str("reference"),
                    v_str("verification_phrase"),
                    v_str("version")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/users/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("users")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(9,
                    cmap(4,
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$OBJECT`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("email"),
                      "orig", v_str("email"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("first_name"),
                      "orig", v_str("first_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("last_name"),
                      "orig", v_str("last_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$OBJECT`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("phone"),
                      "orig", v_str("phone"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("send_welcome_email"),
                      "orig", v_str("send_welcome_email"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("username"),
                      "orig", v_str("username"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("client"),
                    v_str("email"),
                    v_str("first_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("last_name"),
                    v_str("partner"),
                    v_str("phone"),
                    v_str("send_welcome_email"),
                    v_str("username")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/clients/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("clients")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(8,
                    cmap(4,
                      "name", v_str("billing_id"),
                      "orig", v_str("billing_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("contact_id"),
                      "orig", v_str("contact_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("direct_partner_id"),
                      "orig", v_str("direct_partner_id"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("direct_partner_name"),
                      "orig", v_str("direct_partner_name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("is_active"),
                      "orig", v_str("is_active"),
                      "type", v_str("`$BOOLEAN`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("mid"),
                      "orig", v_str("mid"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("name"),
                      "orig", v_str("name"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("version"),
                      "orig", v_str("version"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(9,
                    v_str("billing_id"),
                    v_str("contact_id"),
                    v_str("direct_partner_id"),
                    v_str("direct_partner_name"),
                    v_str("id"),
                    v_str("is_active"),
                    v_str("mid"),
                    v_str("name"),
                    v_str("version"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "user", cmap(5,
        "fields", clist(13,
          cmap(4,
            "name", v_str("client"),
            "title", v_str("Client"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Client resource.")),
          cmap(5,
            "name", v_str("created"),
            "title", v_str("Created"),
            "type", v_str("`$STRING`"),
            "short", v_str("Creation timestamp in ISO 8601 format."),
            "format", v_str("date-time")),
          cmap(3,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("This resource's unique identifier."),
            "format", v_str("int64")),
          cmap(3,
            "name", v_str("isActive"),
            "title", v_str("Is Active"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("modified"),
            "title", v_str("Modified"),
            "type", v_str("`$STRING`"),
            "short", v_str("Last modified timestamp."),
            "format", v_str("date-time")),
          cmap(4,
            "name", v_str("partner"),
            "title", v_str("Partner"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated Partner.")),
          cmap(3,
            "name", v_str("phone"),
            "title", v_str("Phone"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("userName"),
            "title", v_str("User Name"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("userRole"),
            "title", v_str("User Role"),
            "type", v_str("`$OBJECT`"),
            "short", v_str("Reference to the associated User Role.")),
          cmap(4,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("The number of times that this resource has been updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("user"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("users")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_audit_new(void);
Feature* feature_clienttrack_new(void);
Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_log_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_telemetry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
