(* BluefinShieldconexMgmt SDK utility: prepare_auth.
 *
 * GENERATED by @voxgig/sdkgen (src/cmp/ocaml/PrepareAuth_ocaml.ts), not
 * copied from tm/ocaml - WHERE the credential goes and UNDER WHAT NAME is a
 * fact about this API, and a template can hold only one answer. This SDK's
 * scheme places it in the `authorization` header.
 *
 * Sdk_runtime binds `prepare_auth_util` to this one and registers it in the
 * utility record, so every caller reaches it exactly as before. *)

open Voxgig_struct
open Sdk_types
open Sdk_helpers

(* THE PLACEMENT THIS SDK WAS GENERATED FOR, DECLARED rather than left
 * implicit in the code below.
 *
 *   cred_active  false only for main.kit.config.auth.active: false
 *   cred_where   header | query | cookie
 *   cred_name    the key used - ALREADY LOWER-CASED for a header, because
 *                every header key the runtime writes is; verbatim for a
 *                query parameter or a cookie, which are case-sensitive
 *
 * They exist so the SHIPPED suite can hold the runtime to its own contract
 * instead of guessing at it: test/t_pipeline.ml's four `prepare_auth.*`
 * cases hardcoded `spec.headers["authorization"]`, so they failed on any
 * SDK whose scheme is not a header - precisely the SDK this change exists to
 * make work. Reading them is not circular: the assertions still drive the
 * real prepare_auth and check the bag, key and value it actually wrote. *)
let cred_active = true
let cred_where = "header"
let cred_name = "authorization"

let option_apikey = "apikey"
let option_secret = "secret"
let not_found = "__NOTFOUND__"

let b64_alphabet =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

let base64_encode (text : string) : string =
  let n = String.length text in
  let buf = Buffer.create (((n + 2) / 3) * 4) in
  let i = ref 0 in
  while !i < n do
    let rest = n - !i in
    let a = Char.code text.[!i] in
    let b = if 1 < rest then Char.code text.[!i + 1] else 0 in
    let c = if 2 < rest then Char.code text.[!i + 2] else 0 in
    let word = (a lsl 16) lor (b lsl 8) lor c in
    Buffer.add_char buf b64_alphabet.[(word lsr 18) land 0x3f];
    Buffer.add_char buf b64_alphabet.[(word lsr 12) land 0x3f];
    (* One trailing source byte yields two characters and "==", two yield
     * three and "=". *)
    Buffer.add_char buf (if 1 < rest then b64_alphabet.[(word lsr 6) land 0x3f] else '=');
    Buffer.add_char buf (if 2 < rest then b64_alphabet.[word land 0x3f] else '=');
    i := !i + 3
  done;
  Buffer.contents buf

let prepare_auth_util (ctx : ctx) : (spec option * sdk_error option) =
  match ctx.c_spec with
  | None -> (None, Some (ctx_make_error ctx "auth_no_spec" "Expected context spec property to be defined."))
  | Some spec ->
    let headers = spec.sp_headers in
    let options = client_options_map (cc ctx) in
    (match getp options "auth" with
     (* `auth: null` is the documented suppression, and a public API that
      * needs no auth omits the block entirely. Both land here. *)
     | Noval | Null -> ignore (delprop headers (Str cred_name)); (Some spec, None)
     | _ ->
       let apikey = getprop ~alt:(Str not_found) options (Str option_apikey) in
       let is_notfound = (match apikey with Str s -> s = not_found | _ -> false) in
       let no_apikey = is_notfound || is_noval apikey || apikey = Str "" in
       if (match getpath_s options "auth.basic" with Bool b -> b | _ -> false) then begin
         (* True HTTP Basic Auth needs TWO credentials, base64-joined - a
          * single token in the header (the branch below) can never
          * authenticate against an API that actually checks
          * `Authorization: Basic base64(user:pass)`. *)
         let secret = getprop ~alt:(Str not_found) options (Str option_secret) in
         let no_secret =
           (match secret with Str s -> s = not_found | _ -> false)
           || is_noval secret || secret = Str "" in
         if no_apikey || no_secret then
           ignore (delprop headers (Str cred_name))
         else begin
           let auth_prefix = match getpath_s options "auth.prefix" with Str s -> s | _ -> "" in
           let apikey_val = match apikey with Str s -> s | _ -> "" in
           let secret_val = match secret with Str s -> s | _ -> "" in
           let joined = base64_encode (apikey_val ^ ":" ^ secret_val) in
           setp headers cred_name
             (Str (if auth_prefix <> "" then auth_prefix ^ " " ^ joined else joined))
         end
       end
       else
       if no_apikey then
         ignore (delprop headers (Str cred_name))
       else begin
         let auth_prefix = match getpath_s options "auth.prefix" with Str s -> s | _ -> "" in
         let apikey_val = match apikey with Str s -> s | _ -> "" in
         (* Empty prefix (a raw apiKey credential) must not add a leading space. *)
         let authval = if auth_prefix <> "" then auth_prefix ^ " " ^ apikey_val else apikey_val in
         setp headers cred_name (Str authval)
       end;
       (Some spec, None))
