-- BluefinShieldconexMgmt SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , client
  , clone
  , partner
  , template
  , transaction
  , update_result
  , user
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The Client entity bound to this client.
client :: Client -> Value -> IO Entity
client client entopts = F.makeEntity client "client" entopts

-- | The Clone entity bound to this client.
clone :: Client -> Value -> IO Entity
clone client entopts = F.makeEntity client "clone" entopts

-- | The Partner entity bound to this client.
partner :: Client -> Value -> IO Entity
partner client entopts = F.makeEntity client "partner" entopts

-- | The Template entity bound to this client.
template :: Client -> Value -> IO Entity
template client entopts = F.makeEntity client "template" entopts

-- | The Transaction entity bound to this client.
transaction :: Client -> Value -> IO Entity
transaction client entopts = F.makeEntity client "transaction" entopts

-- | The UpdateResult entity bound to this client.
update_result :: Client -> Value -> IO Entity
update_result client entopts = F.makeEntity client "update_result" entopts

-- | The User entity bound to this client.
user :: Client -> Value -> IO Entity
user client entopts = F.makeEntity client "user" entopts

