-- BluefinShieldconexMgmt SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    -- client: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/client/ClientTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - client: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "client"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Client.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"client.list offline -> {n} seeded"
        else fail s!"client.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Client.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"client.load offline (id={wid})"
          else fail s!"client.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "client"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Client.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "client.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Client.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"client.create/load offline (id={cid})"
            else fail s!"client.create/load offline mismatch"
            let _ ← Client.remove tclient m2 (← emptyMap)
            let gone ← Client.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"client.remove offline: still present"
            | _ => pass s!"client.remove offline (id={cid})"
)
    -- partner: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/partner/PartnerTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - partner: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "partner"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Partner.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"partner.list offline -> {n} seeded"
        else fail s!"partner.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Partner.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"partner.load offline (id={wid})"
          else fail s!"partner.load offline: got {gid}, want {wid}"
)
    -- template: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/template/TemplateTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - template: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "template"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Template.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"template.list offline -> {n} seeded"
        else fail s!"template.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Template.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"template.load offline (id={wid})"
          else fail s!"template.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "template"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Template.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "template.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Template.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"template.create/load offline (id={cid})"
            else fail s!"template.create/load offline mismatch"
            let _ ← Template.remove tclient m2 (← emptyMap)
            let gone ← Template.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"template.remove offline: still present"
            | _ => pass s!"template.remove offline (id={cid})"
)
    -- transaction: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/transaction/TransactionTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - transaction: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "transaction"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Transaction.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"transaction.list offline -> {n} seeded"
        else fail s!"transaction.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Transaction.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"transaction.load offline (id={wid})"
          else fail s!"transaction.load offline: got {gid}, want {wid}"
)
    -- update_result: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/update_result/UpdateResultTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - update_result: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "update_result"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Update_result.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"update_result.list offline -> {n} seeded"
        else fail s!"update_result.list offline: got {n}, want {ids.size}"
)
    -- user: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/user/UserTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - user: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "user"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← User.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"user.load offline (id={wid})"
          else fail s!"user.load offline: got {gid}, want {wid}"
)
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      -- client: list smoke
      (do
        let items ← Client.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"client.list -> {(← listItems lid).size} items"
        | _ => fail "client.list did not return a list")
      -- client: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{}"
        let created ← Client.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "client.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Client.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"client.create/load round-trip (id={nid})"
          else fail s!"client.load mismatch: {bid} != {nid}"
          let _ ← Client.remove client m (← emptyMap)
          pass s!"client.remove (id={nid})")
      -- partner: list smoke
      (do
        let items ← Partner.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"partner.list -> {(← listItems lid).size} items"
        | _ => fail "partner.list did not return a list")
      -- template: list smoke
      (do
        let items ← Template.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"template.list -> {(← listItems lid).size} items"
        | _ => fail "template.list did not return a list")
      -- template: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{}"
        let created ← Template.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "template.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Template.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"template.create/load round-trip (id={nid})"
          else fail s!"template.load mismatch: {bid} != {nid}"
          let _ ← Template.remove client m (← emptyMap)
          pass s!"template.remove (id={nid})")
      -- transaction: list smoke
      (do
        let items ← Transaction.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"transaction.list -> {(← listItems lid).size} items"
        | _ => fail "transaction.list did not return a list")
      -- update_result: list smoke
      (do
        let items ← Update_result.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"update_result.list -> {(← listItems lid).size} items"
        | _ => fail "update_result.list did not return a list")
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
