import 'feature/base/BaseFeature.dart';
import 'feature/test/TestFeature.dart';


// ignore: non_constant_identifier_names
final Map<String, BaseFeature Function()> FEATURE_CLASS = {
    'test': () => TestFeature(),

};

class Config {
  BaseFeature makeFeature(String fn) {
    final fc = FEATURE_CLASS[fn];
    if (null == fc) {
      // TODO: errors etc
      throw StateError('Unknown feature: ' + fn);
    }
    return fc();
  }

  final Map<String, dynamic> main = <String, dynamic>{
    'name': 'ProjectName',
  };

  final Map<String, dynamic> feature = <String, dynamic>{
        'test': <String, dynamic>{
      'options': <String, dynamic>{
        'active': false,
      },
    },

  };

  final Map<String, dynamic> options = <String, dynamic>{
    'base': 'https://portal-cert.shieldconex.com:4010/api/v1',

    'auth': <String, dynamic>{
      'prefix': 'Basic',
    },

    'headers': <String, dynamic>{
      'content-type': 'application/json',
    },

    'entity': <String, dynamic>{
            'client': <String, dynamic>{},
      'clone': <String, dynamic>{},
      'partner': <String, dynamic>{},
      'template': <String, dynamic>{},
      'transaction': <String, dynamic>{},
      'update_result': <String, dynamic>{},
      'user': <String, dynamic>{},

    }
  };

  final Map<String, dynamic> entity = <String, dynamic>{
    'client': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'billing_id',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'contact',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
            'list': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
          },
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'created',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'direct_partner',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
          },
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'is_active',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'mid',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'modified',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'name',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$STRING`',
            },
          },
          'req': false,
          'type': '`\$STRING`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'version',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 10,
        },
      ],
      'name': 'client',
      'op': <String, dynamic>{
        'create': <String, dynamic>{
          'input': 'data',
          'name': 'create',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'billing_id',
                    'orig': 'billing_id',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_email',
                    'orig': 'contact_email',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_first_name',
                    'orig': 'contact_first_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_is_active',
                    'orig': 'contact_is_active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_last_name',
                    'orig': 'contact_last_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_phone',
                    'orig': 'contact_phone',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_send_welcome_email',
                    'orig': 'contact_send_welcome_email',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_user_name',
                    'orig': 'contact_user_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_user_role',
                    'orig': 'contact_user_role',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'direct_partner_id',
                    'orig': 'direct_partner_id',
                    'reqd': true,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'direct_partner_name',
                    'orig': 'direct_partner_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'mid',
                    'orig': 'mid',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'POST',
              'orig': '/clients',
              'parts': <dynamic>[
                'clients',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'billing_id',
                  'contact_email',
                  'contact_first_name',
                  'contact_is_active',
                  'contact_last_name',
                  'contact_phone',
                  'contact_send_welcome_email',
                  'contact_user_name',
                  'contact_user_role',
                  'direct_partner_id',
                  'direct_partner_name',
                  'is_active',
                  'mid',
                  'name',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'create',
        },
        'list': <String, dynamic>{
          'input': 'data',
          'name': 'list',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 0,
                    'kind': 'query',
                    'name': 'skip',
                    'orig': 'skip',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 10,
                    'kind': 'query',
                    'name': 'take',
                    'orig': 'take',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/clients',
              'parts': <dynamic>[
                'clients',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'partner',
                  'skip',
                  'take',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'list',
        },
        'load': <String, dynamic>{
          'input': 'data',
          'name': 'load',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'GET',
              'orig': '/clients/{id}',
              'parts': <dynamic>[
                'clients',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'load',
        },
        'remove': <String, dynamic>{
          'input': 'data',
          'name': 'remove',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'DELETE',
              'orig': '/clients/{id}',
              'parts': <dynamic>[
                'clients',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'remove',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
    'clone': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 1,
        },
      ],
      'name': 'clone',
      'op': <String, dynamic>{
        'create': <String, dynamic>{
          'input': 'data',
          'name': 'create',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'template_id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'POST',
              'orig': '/templates/{id}/clone',
              'parts': <dynamic>[
                'templates',
                '{template_id}',
                'clone',
              ],
              'rename': <String, dynamic>{
                'param': <String, dynamic>{
                  'id': 'template_id',
                },
              },
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'template_id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'create',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[
          <dynamic>[
            'template',
          ],
        ],
      },
    },
    'partner': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'billing_id',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'contact',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
            'list': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
          },
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'created',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'is_active',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'modified',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'name',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$STRING`',
            },
          },
          'req': false,
          'type': '`\$STRING`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'parent',
          'op': <String, dynamic>{
            'create': <String, dynamic>{
              'req': true,
              'type': '`\$OBJECT`',
            },
          },
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'reference',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'verification_phrase',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'version',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 10,
        },
      ],
      'name': 'partner',
      'op': <String, dynamic>{
        'create': <String, dynamic>{
          'input': 'data',
          'name': 'create',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'billing_id',
                    'orig': 'billing_id',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_email',
                    'orig': 'contact_email',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_first_name',
                    'orig': 'contact_first_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_is_active',
                    'orig': 'contact_is_active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_last_name',
                    'orig': 'contact_last_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_phone',
                    'orig': 'contact_phone',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_send_welcome_email',
                    'orig': 'contact_send_welcome_email',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_user_name',
                    'orig': 'contact_user_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_user_role',
                    'orig': 'contact_user_role',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'parent_id',
                    'orig': 'parent_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'parent_name',
                    'orig': 'parent_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'reference',
                    'orig': 'reference',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'verification_phrase',
                    'orig': 'verification_phrase',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'POST',
              'orig': '/partners',
              'parts': <dynamic>[
                'partners',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'billing_id',
                  'contact_email',
                  'contact_first_name',
                  'contact_is_active',
                  'contact_last_name',
                  'contact_phone',
                  'contact_send_welcome_email',
                  'contact_user_name',
                  'contact_user_role',
                  'is_active',
                  'name',
                  'parent_id',
                  'parent_name',
                  'reference',
                  'verification_phrase',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'create',
        },
        'list': <String, dynamic>{
          'input': 'data',
          'name': 'list',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 0,
                    'kind': 'query',
                    'name': 'skip',
                    'orig': 'skip',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 10,
                    'kind': 'query',
                    'name': 'take',
                    'orig': 'take',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/partners',
              'parts': <dynamic>[
                'partners',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'partner',
                  'skip',
                  'take',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'list',
        },
        'load': <String, dynamic>{
          'input': 'data',
          'name': 'load',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'GET',
              'orig': '/partners/{id}',
              'parts': <dynamic>[
                'partners',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'load',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
    'template': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'access_mode',
          'req': false,
          'type': '`\$ANY`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'active',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'client',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'field_template',
          'req': false,
          'type': '`\$ARRAY`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'option',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'reference',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'type',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'version',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 10,
        },
      ],
      'name': 'template',
      'op': <String, dynamic>{
        'create': <String, dynamic>{
          'input': 'data',
          'name': 'create',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'access_mode',
                    'orig': 'access_mode',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'active',
                    'orig': 'active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client_id',
                    'orig': 'client_id',
                    'reqd': true,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client_name',
                    'orig': 'client_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'field_template',
                    'orig': 'field_template',
                    'reqd': false,
                    'type': '`\$ARRAY`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_custom_style',
                    'orig': 'options_custom_style',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_custom_style_file',
                    'orig': 'options_custom_style_file',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_domain',
                    'orig': 'options_domain',
                    'reqd': false,
                    'type': '`\$ARRAY`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_active_from',
                    'orig': 'options_security_active_from',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_active_to',
                    'orig': 'options_security_active_to',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_irreversible',
                    'orig': 'options_security_irreversible',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner_id',
                    'orig': 'partner_id',
                    'reqd': true,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner_name',
                    'orig': 'partner_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'reference',
                    'orig': 'reference',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'type',
                    'orig': 'type',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'version',
                    'orig': 'version',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'POST',
              'orig': '/templates',
              'parts': <dynamic>[
                'templates',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'access_mode',
                  'active',
                  'client_id',
                  'client_name',
                  'field_template',
                  'name',
                  'options_custom_style',
                  'options_custom_style_file',
                  'options_domain',
                  'options_security_active_from',
                  'options_security_active_to',
                  'options_security_irreversible',
                  'partner_id',
                  'partner_name',
                  'reference',
                  'type',
                  'version',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'create',
        },
        'list': <String, dynamic>{
          'input': 'data',
          'name': 'list',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client',
                    'orig': 'client',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 0,
                    'kind': 'query',
                    'name': 'skip',
                    'orig': 'skip',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 10,
                    'kind': 'query',
                    'name': 'take',
                    'orig': 'take',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/templates',
              'parts': <dynamic>[
                'templates',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'client',
                  'partner',
                  'skip',
                  'take',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'list',
        },
        'load': <String, dynamic>{
          'input': 'data',
          'name': 'load',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'GET',
              'orig': '/templates/{id}',
              'parts': <dynamic>[
                'templates',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'load',
        },
        'remove': <String, dynamic>{
          'input': 'data',
          'name': 'remove',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'DELETE',
              'orig': '/templates/{id}',
              'parts': <dynamic>[
                'templates',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'remove',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
    'transaction': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'bfid',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'client',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'complete_date',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'direct_partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'err_code',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'err_message',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'ip_address',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'message_id',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'reference',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 10,
        },
        <String, dynamic>{
          'active': true,
          'name': 'success',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 11,
        },
        <String, dynamic>{
          'active': true,
          'name': 'template_id',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 12,
        },
      ],
      'name': 'transaction',
      'op': <String, dynamic>{
        'list': <String, dynamic>{
          'input': 'data',
          'name': 'list',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client',
                    'orig': 'client',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'date_from',
                    'orig': 'date_from',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'date_to',
                    'orig': 'date_to',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'message_id',
                    'orig': 'message_id',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'paging_mode',
                    'orig': 'paging_mode',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'reference',
                    'orig': 'reference',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 0,
                    'kind': 'query',
                    'name': 'skip',
                    'orig': 'skip',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'success',
                    'orig': 'success',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 10,
                    'kind': 'query',
                    'name': 'take',
                    'orig': 'take',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'transaction_type',
                    'orig': 'transaction_type',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/transactions',
              'parts': <dynamic>[
                'transactions',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'client',
                  'date_from',
                  'date_to',
                  'message_id',
                  'paging_mode',
                  'partner',
                  'reference',
                  'skip',
                  'success',
                  'take',
                  'transaction_type',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'list',
        },
        'load': <String, dynamic>{
          'input': 'data',
          'name': 'load',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'transaction_type',
                    'orig': 'transaction_type',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/transactions/{id}',
              'parts': <dynamic>[
                'transactions',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                  'transaction_type',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'load',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
    'update_result': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'billing_id',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'client',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'contact',
          'req': true,
          'type': '`\$OBJECT`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'direct_partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'email',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
          },
          'req': true,
          'type': '`\$STRING`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'first_name',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
          },
          'req': true,
          'type': '`\$STRING`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'is_active',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'last_name',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
          },
          'req': true,
          'type': '`\$STRING`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'mid',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 10,
        },
        <String, dynamic>{
          'active': true,
          'name': 'parent',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 11,
        },
        <String, dynamic>{
          'active': true,
          'name': 'partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 12,
        },
        <String, dynamic>{
          'active': true,
          'name': 'phone',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
          },
          'req': true,
          'type': '`\$STRING`',
          'index\$': 13,
        },
        <String, dynamic>{
          'active': true,
          'name': 'reference',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 14,
        },
        <String, dynamic>{
          'active': true,
          'name': 'send_welcome_email',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 15,
        },
        <String, dynamic>{
          'active': true,
          'name': 'user_name',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$STRING`',
            },
          },
          'req': true,
          'type': '`\$STRING`',
          'index\$': 16,
        },
        <String, dynamic>{
          'active': true,
          'name': 'user_role',
          'op': <String, dynamic>{
            'list': <String, dynamic>{
              'req': false,
              'type': '`\$OBJECT`',
            },
            'update': <String, dynamic>{
              'req': false,
              'type': '`\$OBJECT`',
            },
          },
          'req': true,
          'type': '`\$OBJECT`',
          'index\$': 17,
        },
        <String, dynamic>{
          'active': true,
          'name': 'verification_phrase',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 18,
        },
        <String, dynamic>{
          'active': true,
          'name': 'version',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 19,
        },
      ],
      'name': 'update_result',
      'op': <String, dynamic>{
        'create': <String, dynamic>{
          'input': 'data',
          'name': 'create',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client',
                    'orig': 'client',
                    'reqd': false,
                    'type': '`\$OBJECT`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'email',
                    'orig': 'email',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'first_name',
                    'orig': 'first_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'last_name',
                    'orig': 'last_name',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$OBJECT`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'phone',
                    'orig': 'phone',
                    'reqd': true,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'send_welcome_email',
                    'orig': 'send_welcome_email',
                    'reqd': true,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'user_role',
                    'orig': 'user_role',
                    'reqd': true,
                    'type': '`\$OBJECT`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'username',
                    'orig': 'username',
                    'reqd': true,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'POST',
              'orig': '/users',
              'parts': <dynamic>[
                'users',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'client',
                  'email',
                  'first_name',
                  'is_active',
                  'last_name',
                  'partner',
                  'phone',
                  'send_welcome_email',
                  'user_role',
                  'username',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'create',
        },
        'list': <String, dynamic>{
          'input': 'data',
          'name': 'list',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client',
                    'orig': 'client',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 0,
                    'kind': 'query',
                    'name': 'skip',
                    'orig': 'skip',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'example': 10,
                    'kind': 'query',
                    'name': 'take',
                    'orig': 'take',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'GET',
              'orig': '/users',
              'parts': <dynamic>[
                'users',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'client',
                  'partner',
                  'skip',
                  'take',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'list',
        },
        'update': <String, dynamic>{
          'input': 'data',
          'name': 'update',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'access_mode',
                    'orig': 'access_mode',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'active',
                    'orig': 'active',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client_id',
                    'orig': 'client_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client_name',
                    'orig': 'client_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'field_template',
                    'orig': 'field_template',
                    'reqd': false,
                    'type': '`\$ARRAY`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_custom_style',
                    'orig': 'options_custom_style',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_custom_style_file',
                    'orig': 'options_custom_style_file',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_domain',
                    'orig': 'options_domain',
                    'reqd': false,
                    'type': '`\$ARRAY`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_active_from',
                    'orig': 'options_security_active_from',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_active_to',
                    'orig': 'options_security_active_to',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'options_security_irreversible',
                    'orig': 'options_security_irreversible',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner_id',
                    'orig': 'partner_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner_name',
                    'orig': 'partner_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'reference',
                    'orig': 'reference',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'type',
                    'orig': 'type',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'version',
                    'orig': 'version',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'PATCH',
              'orig': '/templates/{id}',
              'parts': <dynamic>[
                'templates',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'access_mode',
                  'active',
                  'client_id',
                  'client_name',
                  'field_template',
                  'id',
                  'name',
                  'options_custom_style',
                  'options_custom_style_file',
                  'options_domain',
                  'options_security_active_from',
                  'options_security_active_to',
                  'options_security_irreversible',
                  'partner_id',
                  'partner_name',
                  'reference',
                  'type',
                  'version',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'billing_id',
                    'orig': 'billing_id',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_id',
                    'orig': 'contact_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'parent_id',
                    'orig': 'parent_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'parent_name',
                    'orig': 'parent_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'reference',
                    'orig': 'reference',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'verification_phrase',
                    'orig': 'verification_phrase',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'version',
                    'orig': 'version',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'PATCH',
              'orig': '/partners/{id}',
              'parts': <dynamic>[
                'partners',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'billing_id',
                  'contact_id',
                  'id',
                  'is_active',
                  'name',
                  'parent_id',
                  'parent_name',
                  'reference',
                  'verification_phrase',
                  'version',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 1,
            },
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'client',
                    'orig': 'client',
                    'reqd': false,
                    'type': '`\$OBJECT`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'email',
                    'orig': 'email',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'first_name',
                    'orig': 'first_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'last_name',
                    'orig': 'last_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'partner',
                    'orig': 'partner',
                    'reqd': false,
                    'type': '`\$OBJECT`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'phone',
                    'orig': 'phone',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'send_welcome_email',
                    'orig': 'send_welcome_email',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'username',
                    'orig': 'username',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                ],
              },
              'method': 'PATCH',
              'orig': '/users/{id}',
              'parts': <dynamic>[
                'users',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'client',
                  'email',
                  'first_name',
                  'id',
                  'is_active',
                  'last_name',
                  'partner',
                  'phone',
                  'send_welcome_email',
                  'username',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 2,
            },
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
                'query': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'billing_id',
                    'orig': 'billing_id',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'contact_id',
                    'orig': 'contact_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'direct_partner_id',
                    'orig': 'direct_partner_id',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'direct_partner_name',
                    'orig': 'direct_partner_name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'is_active',
                    'orig': 'is_active',
                    'reqd': false,
                    'type': '`\$BOOLEAN`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'mid',
                    'orig': 'mid',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'name',
                    'orig': 'name',
                    'reqd': false,
                    'type': '`\$STRING`',
                  },
                  <String, dynamic>{
                    'active': true,
                    'kind': 'query',
                    'name': 'version',
                    'orig': 'version',
                    'reqd': false,
                    'type': '`\$INTEGER`',
                  },
                ],
              },
              'method': 'PATCH',
              'orig': '/clients/{id}',
              'parts': <dynamic>[
                'clients',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'billing_id',
                  'contact_id',
                  'direct_partner_id',
                  'direct_partner_name',
                  'id',
                  'is_active',
                  'mid',
                  'name',
                  'version',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 3,
            },
          ],
          'key\$': 'update',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
    'user': <String, dynamic>{
      'fields': <dynamic>[
        <String, dynamic>{
          'active': true,
          'name': 'client',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 0,
        },
        <String, dynamic>{
          'active': true,
          'name': 'created',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 1,
        },
        <String, dynamic>{
          'active': true,
          'name': 'email',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 2,
        },
        <String, dynamic>{
          'active': true,
          'name': 'first_name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 3,
        },
        <String, dynamic>{
          'active': true,
          'name': 'id',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 4,
        },
        <String, dynamic>{
          'active': true,
          'name': 'is_active',
          'req': false,
          'type': '`\$BOOLEAN`',
          'index\$': 5,
        },
        <String, dynamic>{
          'active': true,
          'name': 'last_name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 6,
        },
        <String, dynamic>{
          'active': true,
          'name': 'modified',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 7,
        },
        <String, dynamic>{
          'active': true,
          'name': 'partner',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 8,
        },
        <String, dynamic>{
          'active': true,
          'name': 'phone',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 9,
        },
        <String, dynamic>{
          'active': true,
          'name': 'user_name',
          'req': false,
          'type': '`\$STRING`',
          'index\$': 10,
        },
        <String, dynamic>{
          'active': true,
          'name': 'user_role',
          'req': false,
          'type': '`\$OBJECT`',
          'index\$': 11,
        },
        <String, dynamic>{
          'active': true,
          'name': 'version',
          'req': false,
          'type': '`\$INTEGER`',
          'index\$': 12,
        },
      ],
      'name': 'user',
      'op': <String, dynamic>{
        'load': <String, dynamic>{
          'input': 'data',
          'name': 'load',
          'points': <dynamic>[
            <String, dynamic>{
              'active': true,
              'args': <String, dynamic>{
                'params': <dynamic>[
                  <String, dynamic>{
                    'active': true,
                    'kind': 'param',
                    'name': 'id',
                    'orig': 'id',
                    'reqd': true,
                    'type': '`\$STRING`',
                    'index\$': 0,
                  },
                ],
              },
              'method': 'GET',
              'orig': '/users/{id}',
              'parts': <dynamic>[
                'users',
                '{id}',
              ],
              'select': <String, dynamic>{
                'exist': <dynamic>[
                  'id',
                ],
              },
              'transform': <String, dynamic>{
                'req': '`reqdata`',
                'res': '`body`',
              },
              'index\$': 0,
            },
          ],
          'key\$': 'load',
        },
      },
      'relations': <String, dynamic>{
        'ancestors': <dynamic>[],
      },
    },
  };

  // The pipeline context carries the config as a plain map.
  Map<String, dynamic> toMap() => <String, dynamic>{
        'main': main,
        'feature': feature,
        'options': options,
        'entity': entity,
      };
}

final config = Config();
