;; BluefinShieldconexMgmt SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.client :as e-client]
            [sdk.entity.clone :as e-clone]
            [sdk.entity.partner :as e-partner]
            [sdk.entity.template :as e-template]
            [sdk.entity.transaction :as e-transaction]
            [sdk.entity.update_result :as e-update_result]
            [sdk.entity.user :as e-user]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; Client accessor: (client client data)
(defn client [client data] (e-client/make client data))

;; Clone accessor: (clone client data)
(defn clone [client data] (e-clone/make client data))

;; Partner accessor: (partner client data)
(defn partner [client data] (e-partner/make client data))

;; Template accessor: (template client data)
(defn template [client data] (e-template/make client data))

;; Transaction accessor: (transaction client data)
(defn transaction [client data] (e-transaction/make client data))

;; UpdateResult accessor: (update_result client data)
(defn update_result [client data] (e-update_result/make client data))

;; User accessor: (user client data)
(defn user [client data] (e-user/make client data))
