;; BluefinShieldconexMgmt SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "client" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "billingId"
            "short" "Billing ID"
            "type" "`$STRING`")
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`")
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the Client account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "mid"
            "short" "Some Partners will have an merchant ids on their own software offerings."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "short" "The Client's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "client"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_email"
                      "orig" "contact_email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_first_name"
                      "orig" "contact_first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_is_active"
                      "orig" "contact_is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_last_name"
                      "orig" "contact_last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_phone"
                      "orig" "contact_phone"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_send_welcome_email"
                      "orig" "contact_send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_user_name"
                      "orig" "contact_user_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_user_role"
                      "orig" "contact_user_role"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "direct_partner_id"
                      "orig" "direct_partner_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "direct_partner_name"
                      "orig" "direct_partner_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "mid"
                      "orig" "mid"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_email"
                    "contact_first_name"
                    "contact_is_active"
                    "contact_last_name"
                    "contact_phone"
                    "contact_send_welcome_email"
                    "contact_user_name"
                    "contact_user_role"
                    "direct_partner_id"
                    "direct_partner_name"
                    "is_active"
                    "mid"
                    "name"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "clone" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "short" "Unique identifier of newly added element."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "short" "Name of Template"
            "type" "`$STRING`"))
        "name" "clone"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "template_id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/templates/{id}/clone"
                "parts" (vs/jt
                  "templates"
                  "{template_id}"
                  "clone")
                "rename" (vs/jm
                  "param" (vs/jm
                    "id" "template_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "template_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "template"))))
      "partner" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "billingId"
            "short" "The Partner's billing identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`")
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the Parter account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "short" "The Partner's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "parent"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "reference"
            "short" "The Partner's reference string."
            "type" "`$STRING`")
          (vs/jm
            "name" "verificationPhrase"
            "short" "The verification phrase is a message that the Partner creates."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "partner"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_email"
                      "orig" "contact_email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_first_name"
                      "orig" "contact_first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_is_active"
                      "orig" "contact_is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_last_name"
                      "orig" "contact_last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_phone"
                      "orig" "contact_phone"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_send_welcome_email"
                      "orig" "contact_send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_user_name"
                      "orig" "contact_user_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_user_role"
                      "orig" "contact_user_role"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "parent_id"
                      "orig" "parent_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "parent_name"
                      "orig" "parent_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "verification_phrase"
                      "orig" "verification_phrase"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_email"
                    "contact_first_name"
                    "contact_is_active"
                    "contact_last_name"
                    "contact_phone"
                    "contact_send_welcome_email"
                    "contact_user_name"
                    "contact_user_role"
                    "is_active"
                    "name"
                    "parent_id"
                    "parent_name"
                    "reference"
                    "verification_phrase"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "template" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "accessMode"
            "short" "The Template's access mode."
            "type" "`$ANY`")
          (vs/jm
            "name" "active"
            "short" "This property indicates if the Template is active or inactive."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "fieldTemplates"
            "short" "Field Template list items"
            "type" "`$ARRAY`"
            "union" (vs/jm
              "branches" 9
              "count" 1
              "depth" 1))
          (vs/jm
            "name" "id"
            "short" "Unique identifier of newly added element."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "short" "The Template's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "options"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "reference"
            "short" "The Template's unique reference."
            "type" "`$STRING`")
          (vs/jm
            "name" "type"
            "short" "The Template's type."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "template"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "access_mode"
                      "orig" "access_mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "active"
                      "orig" "active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_id"
                      "orig" "client_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_name"
                      "orig" "client_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "field_template"
                      "orig" "field_template"
                      "type" "`$ARRAY`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_custom_style"
                      "orig" "options_custom_style"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_custom_style_file"
                      "orig" "options_custom_style_file"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_domain"
                      "orig" "options_domain"
                      "type" "`$ARRAY`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_active_from"
                      "orig" "options_security_active_from"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_active_to"
                      "orig" "options_security_active_to"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_irreversible"
                      "orig" "options_security_irreversible"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner_id"
                      "orig" "partner_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner_name"
                      "orig" "partner_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "type"
                      "orig" "type"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "POST"
                "orig" "/templates"
                "parts" (vs/jt
                  "templates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "access_mode"
                    "active"
                    "client_id"
                    "client_name"
                    "field_template"
                    "name"
                    "options_custom_style"
                    "options_custom_style_file"
                    "options_domain"
                    "options_security_active_from"
                    "options_security_active_to"
                    "options_security_irreversible"
                    "partner_id"
                    "partner_name"
                    "reference"
                    "type"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/templates"
                "parts" (vs/jt
                  "templates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "bfid"
            "short" "BFID"
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "completeDate"
            "short" "Timestamp from the beginning of the transaction."
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "errCode"
            "short" "The error code that is sent in response to a failed decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "errMessage"
            "short" "The error messge that is sent in response to a failed decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "ipAddress"
            "short" "The IP address of the http client that makes the decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "messageId"
            "short" "Message ID."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "reference"
            "short" "The reference property that the Client includes in the decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "success"
            "short" "The success indicator."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "templateId"
            "short" "The Template's unique identifier."
            "type" "`$STRING`"))
        "name" "transaction"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_from"
                      "orig" "date_from"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_to"
                      "orig" "date_to"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "message_id"
                      "orig" "message_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "paging_mode"
                      "orig" "paging_mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "success"
                      "orig" "success"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "transaction_type"
                      "orig" "transaction_type"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "date_from"
                    "date_to"
                    "message_id"
                    "paging_mode"
                    "partner"
                    "reference"
                    "skip"
                    "success"
                    "take"
                    "transaction_type"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "transaction_type"
                      "orig" "transaction_type"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "transaction_type"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "billingId"
            "short" "The Partner's billing identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "contact"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "directPartner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "email"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$STRING`")
              "update" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "short" "The User's email address."
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$STRING`")
              "update" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "short" "The User's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "Unique identifier of newly added element."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the User account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "lastName"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$STRING`")
              "update" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "short" "The User's Surname."
            "type" "`$STRING`")
          (vs/jm
            "name" "mid"
            "short" "Some Partners will have an merchant ids on their own software offerings."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The Partner's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "parent"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$STRING`")
              "update" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "short" "The User's phone number without dashes, spaces, or brackets (e.g."
            "type" "`$STRING`")
          (vs/jm
            "name" "reference"
            "short" "The Partner's reference string."
            "type" "`$STRING`")
          (vs/jm
            "name" "sendWelcomeEmail"
            "short" "If this property is set to 'true' the newly created user will be sent a welcome email."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "userName"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$STRING`")
              "update" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "short" "The User's unique username."
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "op" (vs/jm
              "list" (vs/jm
                "type" "`$OBJECT`")
              "update" (vs/jm
                "type" "`$OBJECT`"))
            "req" true
            "short" "Reference to the associated User Role."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "verificationPhrase"
            "short" "The verification phrase is a message that the Partner creates."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "update_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$OBJECT`")
                    (vs/jm
                      "kind" "query"
                      "name" "email"
                      "orig" "email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "first_name"
                      "orig" "first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "last_name"
                      "orig" "last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$OBJECT`")
                    (vs/jm
                      "kind" "query"
                      "name" "phone"
                      "orig" "phone"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "send_welcome_email"
                      "orig" "send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "user_role"
                      "orig" "user_role"
                      "reqd" true
                      "type" "`$OBJECT`")
                    (vs/jm
                      "kind" "query"
                      "name" "username"
                      "orig" "username"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "email"
                    "first_name"
                    "is_active"
                    "last_name"
                    "partner"
                    "phone"
                    "send_welcome_email"
                    "user_role"
                    "username"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "access_mode"
                      "orig" "access_mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "active"
                      "orig" "active"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_id"
                      "orig" "client_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_name"
                      "orig" "client_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "field_template"
                      "orig" "field_template"
                      "type" "`$ARRAY`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_custom_style"
                      "orig" "options_custom_style"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_custom_style_file"
                      "orig" "options_custom_style_file"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_domain"
                      "orig" "options_domain"
                      "type" "`$ARRAY`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_active_from"
                      "orig" "options_security_active_from"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_active_to"
                      "orig" "options_security_active_to"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "options_security_irreversible"
                      "orig" "options_security_irreversible"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner_id"
                      "orig" "partner_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner_name"
                      "orig" "partner_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "type"
                      "orig" "type"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "access_mode"
                    "active"
                    "client_id"
                    "client_name"
                    "field_template"
                    "id"
                    "name"
                    "options_custom_style"
                    "options_custom_style_file"
                    "options_domain"
                    "options_security_active_from"
                    "options_security_active_to"
                    "options_security_irreversible"
                    "partner_id"
                    "partner_name"
                    "reference"
                    "type"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_id"
                      "orig" "contact_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "parent_id"
                      "orig" "parent_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "parent_name"
                      "orig" "parent_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "verification_phrase"
                      "orig" "verification_phrase"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_id"
                    "id"
                    "is_active"
                    "name"
                    "parent_id"
                    "parent_name"
                    "reference"
                    "verification_phrase"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$OBJECT`")
                    (vs/jm
                      "kind" "query"
                      "name" "email"
                      "orig" "email"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "first_name"
                      "orig" "first_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "last_name"
                      "orig" "last_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$OBJECT`")
                    (vs/jm
                      "kind" "query"
                      "name" "phone"
                      "orig" "phone"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "send_welcome_email"
                      "orig" "send_welcome_email"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "username"
                      "orig" "username"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "email"
                    "first_name"
                    "id"
                    "is_active"
                    "last_name"
                    "partner"
                    "phone"
                    "send_welcome_email"
                    "username"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "contact_id"
                      "orig" "contact_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "direct_partner_id"
                      "orig" "direct_partner_id"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "direct_partner_name"
                      "orig" "direct_partner_name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "kind" "query"
                      "name" "mid"
                      "orig" "mid"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_id"
                    "direct_partner_id"
                    "direct_partner_name"
                    "id"
                    "is_active"
                    "mid"
                    "name"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "type" "`$STRING`")
          (vs/jm
            "name" "userName"
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "short" "Reference to the associated User Role."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "user"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinShieldconexMgmt")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://portal-cert.shieldconex.com:4010/api/v1"
      "entity" (vs/jm
        "client" (vs/jm)
        "clone" (vs/jm)
        "partner" (vs/jm)
        "template" (vs/jm)
        "transaction" (vs/jm)
        "update_result" (vs/jm)
        "user" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
