;; BluefinShieldconexMgmt SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "client" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "billing_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "contact"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`")
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "created"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "direct_partner"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "is_active"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "mid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "modified"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "name"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "version"
            "req" false
            "type" "`$INTEGER`"))
        "name" "client"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_email"
                      "orig" "contact_email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_first_name"
                      "orig" "contact_first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_is_active"
                      "orig" "contact_is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_last_name"
                      "orig" "contact_last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_phone"
                      "orig" "contact_phone"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_send_welcome_email"
                      "orig" "contact_send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_user_name"
                      "orig" "contact_user_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_user_role"
                      "orig" "contact_user_role"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "direct_partner_id"
                      "orig" "direct_partner_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "direct_partner_name"
                      "orig" "direct_partner_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "mid"
                      "orig" "mid"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_email"
                    "contact_first_name"
                    "contact_is_active"
                    "contact_last_name"
                    "contact_phone"
                    "contact_send_welcome_email"
                    "contact_user_name"
                    "contact_user_role"
                    "direct_partner_id"
                    "direct_partner_name"
                    "is_active"
                    "mid"
                    "name"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "GET"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "clone" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "name"
            "req" false
            "type" "`$STRING`"))
        "name" "clone"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "template_id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/templates/{id}/clone"
                "parts" (vs/jt
                  "templates"
                  "{template_id}"
                  "clone")
                "rename" (vs/jm
                  "param" (vs/jm
                    "id" "template_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "template_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "template"))))
      "partner" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "billing_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "contact"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`")
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "created"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "is_active"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "modified"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "name"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "parent"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "verification_phrase"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "version"
            "req" false
            "type" "`$INTEGER`"))
        "name" "partner"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_email"
                      "orig" "contact_email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_first_name"
                      "orig" "contact_first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_is_active"
                      "orig" "contact_is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_last_name"
                      "orig" "contact_last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_phone"
                      "orig" "contact_phone"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_send_welcome_email"
                      "orig" "contact_send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_user_name"
                      "orig" "contact_user_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_user_role"
                      "orig" "contact_user_role"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "parent_id"
                      "orig" "parent_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "parent_name"
                      "orig" "parent_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "verification_phrase"
                      "orig" "verification_phrase"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_email"
                    "contact_first_name"
                    "contact_is_active"
                    "contact_last_name"
                    "contact_phone"
                    "contact_send_welcome_email"
                    "contact_user_name"
                    "contact_user_role"
                    "is_active"
                    "name"
                    "parent_id"
                    "parent_name"
                    "reference"
                    "verification_phrase"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "GET"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "template" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "access_mode"
            "req" false
            "type" "`$ANY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "active"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "client"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "field_template"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "option"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "type"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "version"
            "req" false
            "type" "`$INTEGER`"))
        "name" "template"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "access_mode"
                      "orig" "access_mode"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "active"
                      "orig" "active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client_id"
                      "orig" "client_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client_name"
                      "orig" "client_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_template"
                      "orig" "field_template"
                      "reqd" false
                      "type" "`$ARRAY`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_custom_style"
                      "orig" "options_custom_style"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_custom_style_file"
                      "orig" "options_custom_style_file"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_domain"
                      "orig" "options_domain"
                      "reqd" false
                      "type" "`$ARRAY`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_active_from"
                      "orig" "options_security_active_from"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_active_to"
                      "orig" "options_security_active_to"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_irreversible"
                      "orig" "options_security_irreversible"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_id"
                      "orig" "partner_id"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_name"
                      "orig" "partner_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "type"
                      "orig" "type"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "POST"
                "orig" "/templates"
                "parts" (vs/jt
                  "templates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "access_mode"
                    "active"
                    "client_id"
                    "client_name"
                    "field_template"
                    "name"
                    "options_custom_style"
                    "options_custom_style_file"
                    "options_domain"
                    "options_security_active_from"
                    "options_security_active_to"
                    "options_security_irreversible"
                    "partner_id"
                    "partner_name"
                    "reference"
                    "type"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "GET"
                "orig" "/templates"
                "parts" (vs/jt
                  "templates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "bfid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "client"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "complete_date"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "direct_partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "err_code"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "err_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "ip_address"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "success"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "template_id"
            "req" false
            "type" "`$STRING`"))
        "name" "transaction"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "date_from"
                      "orig" "date_from"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "date_to"
                      "orig" "date_to"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "message_id"
                      "orig" "message_id"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "paging_mode"
                      "orig" "paging_mode"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "success"
                      "orig" "success"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "transaction_type"
                      "orig" "transaction_type"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "date_from"
                    "date_to"
                    "message_id"
                    "paging_mode"
                    "partner"
                    "reference"
                    "skip"
                    "success"
                    "take"
                    "transaction_type"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "transaction_type"
                      "orig" "transaction_type"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "transaction_type"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "billing_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "client"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "contact"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "direct_partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "email"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "first_name"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "is_active"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "last_name"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "mid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "parent"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "phone"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "send_welcome_email"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "user_name"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "user_role"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$OBJECT`")
              "update" (vs/jm
                "req" false
                "type" "`$OBJECT`"))
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "verification_phrase"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "version"
            "req" false
            "type" "`$INTEGER`"))
        "name" "update_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" false
                      "type" "`$OBJECT`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "email"
                      "orig" "email"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "first_name"
                      "orig" "first_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "last_name"
                      "orig" "last_name"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$OBJECT`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "phone"
                      "orig" "phone"
                      "reqd" true
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "send_welcome_email"
                      "orig" "send_welcome_email"
                      "reqd" true
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "user_role"
                      "orig" "user_role"
                      "reqd" true
                      "type" "`$OBJECT`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "username"
                      "orig" "username"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "email"
                    "first_name"
                    "is_active"
                    "last_name"
                    "partner"
                    "phone"
                    "send_welcome_email"
                    "user_role"
                    "username"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "GET"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "access_mode"
                      "orig" "access_mode"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "active"
                      "orig" "active"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client_id"
                      "orig" "client_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client_name"
                      "orig" "client_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_template"
                      "orig" "field_template"
                      "reqd" false
                      "type" "`$ARRAY`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_custom_style"
                      "orig" "options_custom_style"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_custom_style_file"
                      "orig" "options_custom_style_file"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_domain"
                      "orig" "options_domain"
                      "reqd" false
                      "type" "`$ARRAY`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_active_from"
                      "orig" "options_security_active_from"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_active_to"
                      "orig" "options_security_active_to"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "options_security_irreversible"
                      "orig" "options_security_irreversible"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_id"
                      "orig" "partner_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_name"
                      "orig" "partner_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "type"
                      "orig" "type"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/templates/{id}"
                "parts" (vs/jt
                  "templates"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "access_mode"
                    "active"
                    "client_id"
                    "client_name"
                    "field_template"
                    "id"
                    "name"
                    "options_custom_style"
                    "options_custom_style_file"
                    "options_domain"
                    "options_security_active_from"
                    "options_security_active_to"
                    "options_security_irreversible"
                    "partner_id"
                    "partner_name"
                    "reference"
                    "type"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_id"
                      "orig" "contact_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "parent_id"
                      "orig" "parent_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "parent_name"
                      "orig" "parent_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "verification_phrase"
                      "orig" "verification_phrase"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 1
                "method" "PATCH"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_id"
                    "id"
                    "is_active"
                    "name"
                    "parent_id"
                    "parent_name"
                    "reference"
                    "verification_phrase"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" false
                      "type" "`$OBJECT`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "email"
                      "orig" "email"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "first_name"
                      "orig" "first_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "last_name"
                      "orig" "last_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" false
                      "type" "`$OBJECT`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "phone"
                      "orig" "phone"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "send_welcome_email"
                      "orig" "send_welcome_email"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "username"
                      "orig" "username"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 2
                "method" "PATCH"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "email"
                    "first_name"
                    "id"
                    "is_active"
                    "last_name"
                    "partner"
                    "phone"
                    "send_welcome_email"
                    "username"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "billing_id"
                      "orig" "billing_id"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "contact_id"
                      "orig" "contact_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "direct_partner_id"
                      "orig" "direct_partner_id"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "direct_partner_name"
                      "orig" "direct_partner_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "is_active"
                      "orig" "is_active"
                      "reqd" false
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "mid"
                      "orig" "mid"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "name"
                      "orig" "name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "version"
                      "orig" "version"
                      "reqd" false
                      "type" "`$INTEGER`")))
                "index$" 3
                "method" "PATCH"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "billing_id"
                    "contact_id"
                    "direct_partner_id"
                    "direct_partner_name"
                    "id"
                    "is_active"
                    "mid"
                    "name"
                    "version"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "created"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "first_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "id"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "is_active"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "last_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "modified"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "partner"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "phone"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "user_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "user_role"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "version"
            "req" false
            "type" "`$INTEGER`"))
        "name" "user"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinShieldconexMgmt")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://portal-cert.shieldconex.com:4010/api/v1"
      "entity" (vs/jm
        "client" (vs/jm)
        "clone" (vs/jm)
        "partner" (vs/jm)
        "template" (vs/jm)
        "transaction" (vs/jm)
        "update_result" (vs/jm)
        "user" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
