;; BluefinShieldconexMgmt SDK: where the credential goes (generated by @voxgig/sdkgen).
;;
;; PART OF THE sdk.core NAMESPACE, not a namespace of its own: core.clj reads
;; this file with `(load "prepare_auth")` at the point u-prepare-auth used to
;; be defined, so oget / ctx-error / client-options-map are already in scope
;; and base-utility-map's `:prepare-auth u-prepare-auth` still resolves.
(in-ns 'sdk.core)

(def HEADER-AUTH "authorization")
(def OPTION-APIKEY "apikey")
(def OPTION-SECRET "secret")
(def NOT-FOUND "__NOTFOUND__")

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        (let [headers (oget spec :headers)
              options (client-options-map (oget ctx :client))]
          (if (nil? (vs/getprop options "auth"))
            ;; Public APIs that need no auth omit the options.auth block entirely.
            (do (vs/delprop headers HEADER-AUTH) [spec nil])
            (let [apikey (vs/getprop options OPTION-APIKEY NOT-FOUND)]
              ;; True HTTP Basic Auth needs TWO credentials, base64-joined - a
              ;; single token in the header (the branch below) can never
              ;; authenticate against an API that actually checks
              ;; `Authorization: Basic base64(user:pass)`.
              (if (= true (vs/getpath options "auth.basic"))
                (let [secret (vs/getprop options OPTION-SECRET NOT-FOUND)
                      missing? (fn [v] (or (nil? v)
                                           (and (string? v) (or (= v NOT-FOUND) (= v "")))))]
                  (if (or (missing? apikey) (missing? secret))
                    (vs/delprop headers HEADER-AUTH)
                    (let [auth-prefix (or (vs/getpath options "auth.prefix") "")
                          b64 (.encodeToString (java.util.Base64/getEncoder)
                                               (.getBytes ^String (str apikey ":" secret) "UTF-8"))]
                      (.put ^java.util.Map headers HEADER-AUTH
                            (if (= auth-prefix "") b64 (str auth-prefix " " b64))))))
                (if (or (nil? apikey) (and (string? apikey) (or (= apikey NOT-FOUND) (= apikey ""))))
                  (vs/delprop headers HEADER-AUTH)
                  (let [auth-prefix (or (vs/getpath options "auth.prefix") "")
                        apikey-val (if (string? apikey) apikey "")]
                    (.put ^java.util.Map headers HEADER-AUTH
                          (if (= auth-prefix "") apikey-val (str auth-prefix " " apikey-val))))))
              [spec nil]))))))
